#pragma config(Sensor, S1,     corEsq,         sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S2,     corDir,         sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S3,     ultraFrente,    sensorEV3_Ultrasonic)
#pragma config(Sensor, S4,     ultraCurva,     sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          traz,          tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          esquerda,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          direita,       tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void motorg (int grausE, int forcae , int grausD, int forcad)
{
	moveMotorTarget(esquerda,grausE,forcae);
	moveMotorTarget(direita,grausD,forcad);
	waitUntilMotorStop(esquerda);
	waitUntilMotorStop(direita);
}

int distF, erro, vnD, vnE, luzE, luzD, FE, FD, lastErro, distL;

float kp=2.2;
float kd=15;

bool verdeFalsoR;

int graus;
int Fmin=35;
int grause;
int controle;





int pretoE=29;
int pretoD=23;//de 15 ate 32


int brancoE=343;
int brancoD=281;



int verdeE= 31;
int verdeD=25;


int cinzaE=155;
int cinzaD=122;


int cinzaSE=170;
int cinzaSD=170;
int ladoObst=1;


int FminO=20;
bool verdeFalsoL;
bool rampa3;
int sala33;
int controle1;
float kpp=0.3;

long RedE, RedD, GreenE, GreenD, BlueE, BlueD;

task sensores() ;//pronta
task tela() ;//pronta
task seguir();//pronta
task obstaculo();//pronto
task verdE();//pronto
task verdD();//pronto
task versala3Inicio();//pronta
task sala3();//pronta apenas fazer 2 varedura
task versala3Rampa();//pronta
task verdeFalsoE();//pronta
task verdeFalsoD();//pronta


task main()

{



	motor(traz)=-100;
	sleep(2000);
	motor(traz)=0;
	setMotorBrakeMode(traz,0);

	startTask(sensores);
	sleep(500);
	startTask (tela);
	while(1)
	{
		if(getButtonPress(buttonRight))
		{




			startTask(seguir);
			startTask(obstaculo);
			startTask(verdE);
			startTask(verdD);
			startTask(verdeFalsoD);
			startTask(verdeFalsoE);
			startTask(versala3Inicio);
			startTask(versala3Rampa);
			//startTask(curva90);
		}
		sleep(10);
	}//fim do while

}//fim da task mein

task sensores()
{
	while(1)
	{
		luzE=SensorValue[corEsq];//descobre valor dos sensore Direito
		luzD=SensorValue[corDir];//descobre valor do sensor Esquerdo
		distF=SensorValue[ultraFrente];//descobre valor do sensor do Sensor da Frente
		distL=SensorValue[ultraCurva];//descobre valor do sensor Lateral
		getColorRGB(corDir,RedD,GreenD,BlueD);//descobre valor do RGB
		getColorRGB(corEsq, RedE, GreenE,BlueE);//descobre valor do sensor
		graus=getMotorEncoder(direita);//descobre valor do ENCOLDERDIREITO
		grause=getMotorEncoder(esquerda);//descobre valor do ENCONDERESQUERO
		sleep(1);
	}
}
task tela()
{
	while(1)



	{
		//displayBigTextLine(2,"RedD: %d",RedD);
		//	displayBigTextLine(4,"RedE: %d",RedE);
		//	displayBigTextLine(6,"GreenD:%d",GreenD);
		//displayBigTextLine(8,"GreenE:%d",GreenE);

		displayBigTextLine(8,"distF: %d", distF);//MOSTRA OS VALORES NA TELA
		displayBigTextLine(2,"SensorE: %d",luzE);//MOSTRA OS VALORES NA TELA
		displayBigTextLine(4,"SensorD: %d",luzD);//MOSTRA OS VALORES NA TELA
		displayBigTextLine(6,"encodinho: %d",graus);//MOSTRA OS VALORES NA TELA
		displayBigTextLine(8,"vne:%d",vnE);//MOSTRA OS VALORES NA TELA
		displayBigTextLine(10,"vnd:%d",vnD);//MOSTRA OS VALORES NA TELA
		displayBigTextLine(12,"frente:%d",distF);//MOSTRA OS VALORES NA TELA



		sleep(500);
	}
}



task seguir()//seguir linha
{
	while(1)
	{
		vnE = (100*(luzE-pretoE))/(brancoE-pretoE);//calcula valor normalizado Esquerdo
		vnD = (100*(luzD-pretoD))/(brancoD-pretoD);//calcula valor normalizado Direito

		if (vnD>100) vnD=100;//SE O VALOR DO VND FOR ALTO MOTOR RAPIDO
		if (vnD<0) vnD=0;//se vnd for baixa motor lento
		if (vnE>100) vnE=100;//SE O VALOR DO VNE FOR ALTO MOTOR RAPIDO
		if (vnE<0) vnE=0;//se vnd for baixa motor lento

		erro=vnE-vnD;//descobre erro

		FE=Fmin+(kp*erro)+kd*(erro-lastErro);//descobre força dos motores
		FD=Fmin-(kp*erro)-kd*(erro-lastErro);//descobre força dos motores

		lastErro=erro;//lastErro

		motor[esquerda]=FE;//faz ele anda
		motor[direita]=FD;//faz ele anda

		sleep(10);//quantas vezes ele vai checar o sensor
	}
}







task obstaculo()
{
	while(1)
	{
		if (distF<=4)//se a distancia ficar pequena

		{
			if(ladoObst==1){//curva de 90 para esquerda //
				setSoundVolume(100);
				stopTask(verdeFalsoD);
				stopTask(verdeFalsoE);
				stopTask(verdD);
				stopTask(verdE);                  //paratasks
				stopTask(seguir);
				stopTask(versala3Inicio);
				stopTask(versala3Rampa);
				motor[direita]=0;//parar motores
				motor[esquerda]=0; //parar motores
				sleep(300);
				if(vnD<=93&&controle1==0)//descobre o lado da curva pelo valor normalizado
				{
					controle1=1;
					playTone(1000,100);
					if(distF<=3)//se adistacia quando ver o robo for pequena ela vai para traz
					{playSound(nNumbOfSystemSounds);
						motorg(25,-50,25,-50);
					}
					motorg(27,30,27,30);

					motorg(230,30,230,-30);

					motorg(245,30,245,-30);

					motorg(240,-30,240,-30);

					while((luzD>=pretoD+15||luzE>=pretoE+15) && graus<450) //while do alinhamento
					{
						if(luzD>=pretoD+15&&luzE>=pretoE+15)
						{playSound(soundException);
							motor(esquerda)=7;
							motor(direita)=7;
						}//fim do if td branco
						if(luzD<=pretoD+15)
						{
							playTone(1000,100);
							motor(direita)=-10;
							motor(esquerda)=10;
						}//fim do preto na direita
						if(luzE<=pretoE+15)
						{
							motor(direita)=10;
							motor(esquerda)=-10;
						}//preto no esq
					}//fim do while de alihamento
					motor(direita)=0;
					motor(esquerda)=0;
				}
				if(vnE<=93&&controle1==0)
				{
					playSound(soundBeepBeep);
					setLEDColor(ledOff);
					controle1=1;
					if(distF<=3)
					{

						moveMotorTarget(esquerda, 25,- 30);
						moveMotorTarget(direita, 25,- 30);
						waitUntilMotorStop(esquerda);
						waitUntilMotorStop(direita);
					}
					moveMotorTarget(esquerda, 20, 30);
					moveMotorTarget(direita, 20, 30);
					waitUntilMotorStop(esquerda);
					waitUntilMotorStop(direita);
					moveMotorTarget(esquerda, 260, 30);
					moveMotorTarget(direita, 260, -30);
					waitUntilMotorStop(esquerda);
					waitUntilMotorStop(direita);
					while((luzD>=pretoD+15||luzE>=pretoE+15) && graus>-450) //while do alinhamento
					{
						if(luzD>=pretoD+15&&luzE>=pretoE+15)
						{
							motor(esquerda)=-10;
							motor(direita)=-10;

						}//fim do if td branco
						if(luzD<=pretoD+15)
						{
							motor(direita)=10;
							motor(esquerda)=-10;
						}//fim do preto na direita
						if(luzE<=pretoE+15)
						{
							motor(direita)=-10;
							motor(esquerda)=10;
						}//preto no esq
					}//fim do while de alihamento
					motor(esquerda)=0;
					motor(direita)=0;
				}
				if(vnD>93&&vnE>93)
				{
					motorg(380,30,380,-30);
					while((luzD>=pretoD+15||luzE>=pretoE+15) && graus>-450) //while do alinhamento
					{
						if(luzD>=pretoD+15&&luzE>=pretoE+15)
						{
							motor(esquerda)=-10;
							motor(direita)=-10;
						}//fim do if td branco
						if(luzD<=pretoD+15)
						{
							motor(direita)=10;
							motor(esquerda)=-10;
						}//fim do preto na direita
						if(luzE<=pretoE+15)
						{
							motor(direita)=-10;
							motor(esquerda)=10;
						}//preto no esq
					}//fim do while de alihamento
					motor(esquerda)=0;
					motor(direita)=0;
				}
				playTone(1000,100);
				controle1=0;
				while(distL>15)
				{
					motor[direita]=30;
					motor[esquerda]=30;
				}
				motor[direita]=0;
				motor[esquerda]=0;
				while(distL<15)
				{
					motor[direita]=30;
					motor[esquerda]=30;
				}
				motor[direita]=0;
				motor[esquerda]=0;
				motorg(380,-30,380,30);
				while(distL>15)
				{

					motor(esquerda)=30;
					motor(direita)=30;
				}
				resetMotorEncoder(direita);
				sleep(100);//reseta o enconder
				while(distL<15)
				{
					motor(esquerda)=30;
					motor(direita)=30;
				}
				motor(esquerda)=0;
				motor(direita)=0;
				graus=getMotorEncoder(direita);
				stopTask(verdD);
				stopTask(verdE);
				motorg(100,-40,100,-40);
				motorg(380,-40,380,40);
				motorg(150,40,150,40);
				while(luzE > pretoE+10)
				{
					motor[esquerda]=30;
					motor[direita]=30;
				}
				motor[esquerda]=0;
				motor[direita]=0;
				motorg(120,40,120,40);
				motorg(380,-30,380,30);
				resetMotorEncoder(direita);
				motorg(30,-30,30,-30);
				clearTimer(T3);
				stopTask(versala3Inicio);
				if(distF>=5)
				{
					while(time1[T3]<500)
					{
						vnE = (100*(luzE-pretoE))/(brancoE-pretoE);//calcula valor normalizado
						vnD = (100*(luzD-pretoD))/(brancoD-pretoD);
						if (vnD>100) vnD=100;
						if (vnD<0) vnD=0;
						if (vnE>100) vnE=100;
						if (vnE<0) vnE=0;
						erro=vnE-vnD;//descobre erro
						FE=Fmin+(kp*erro)+kd*(erro-lastErro);//descobre força ara os motores
						FD=Fmin-(kp*erro)-kd*(erro-lastErro);
						lastErro=erro;//lastErro
						motor[esquerda]=FE;//faz ele anda
						motor[direita]=FD;
						sleep(10);//quantas vezes ele vai checar o sensor
					}
					motor(esquerda)=0;
					motor(direita)=0;
				}
				if(distF<5)
				{
					while(time1[T3]<400)
					{
						vnE = (100*(luzE-pretoE))/(brancoE-pretoE);//calcula valor normalizado
						vnD = (100*(luzD-pretoD))/(brancoD-pretoD);
						if (vnD>100) vnD=100;
						if (vnD<0) vnD=0;
						if (vnE>100) vnE=100;
						if (vnE<0) vnE=0;
						erro=vnE-vnD;//descobre erro
						FE=Fmin+(kp*erro)+kd*(erro-lastErro);//descobre força ara os motores
						FD=Fmin-(kp*erro)-kd*(erro-lastErro);
						lastErro=erro;//lastErro
						motor[esquerda]=FE;//faz ele anda
						motor[direita]=FD;
						sleep(10);//quantas vezes ele vai checar o sensor
					}
					motor(esquerda)=0;
					motor(direita)=0;
				}
				resetMotorEncoder(direita);
				sleep(100);
				controle=0;
				while(graus>=-400 && controle==0)
				{
					motor(esquerda)=-27;
					motor(direita)=-27;
					if(graus<-390)
					{
						controle=5;
					}
					if(luzE<pretoE+20&&luzD>brancoD-70&&controle==0)
					{
						sleep(100);
						if(luzE > verdeE - 15 && luzE < verdeE + 15 && GreenE - RedE > 6 &&  controle==0)
						{
							motor(esquerda)=0;
							motor(direita)=0;
							sleep(100);
							controle=4;
						}
						else
						{
							motor(esquerda)=0;
							motor(direita)=0;
							sleep(100);
							controle=2;
						}
					}
					if(luzD<pretoD+20 && luzE>brancoE-70 && controle==0)
					{
						sleep(100);
						if(luzD > verdeD - 15 && luzD < verdeD + 15 && GreenD - RedD > 6 &&  controle==0)
						{
							motor(esquerda)=0;
							motor(direita)=0;
							sleep(100);
							controle=3;
						}
						else
						{
							motor(esquerda)=0;
							motor(direita)=0;
							sleep(100);
							controle=1;
						}
					}
				}
				motor(esquerda)=0;
				motor(direita)=0;
				if(controle==1)
				{
					motor(esquerda)=0;
					motor(direita)=0;
					motorg(200,-30,200,-30);
					while(luzD>pretoD+15)
					{
						motor(esquerda)=10;
						motor(direita)=10;
					}
					motor(esquerda)=0;//e25
					motor(direita)=0;
					motorg(70,20,70,20);
					motorg(380,20,380,-20);
				}
				if(controle==2)
				{
					motor(esquerda)=0;
					motor(direita)=0;
					motorg(200,-30,200,-30);
					while(luzE>pretoE+15)
					{
						motor(esquerda)=10;
						motor(direita)=10;
					}
					motor(esquerda)=0;//e25
					motor(direita)=0;
					motorg(70,20,70,20);
					motorg(380,-20,380,20);
					playSound(nNumbOfSystemSounds);
				}
				if(controle==3)
				{
					setLEDColor(ledRedFlash);
					motor(esquerda)=0;
					motor(direita)=0;
					playSound(nNumbOfSystemSounds);
					motor(esquerda)=0;
					motor(direita)=0;
					motorg(50,-30,50,-30);
					motorg(380,20,380,-20);
					motorg(20,70,20,70);
				}

				if(controle==4)
				{

					setLEDColor(ledRedFlash);
					motor(esquerda)=0;
					motor(direita)=0;
					playSound(nNumbOfSystemSounds);
					motor(esquerda)=0;
					motor(direita)=0;
					motorg(50,-30,50,-30);
					motorg(380,-30,380,30);
					motorg(70,20,70,20);
				}
				if(controle==5)
				{
					motorg(750,-30,750,30);
					motorg(230,-30,230,-30);
				}
				controle=0;
				startTask(verdeFalsoD);
				startTask(verdeFalsoE);
				startTask(verdE);
				startTask(verdD);
				startTask(versala3Inicio);
				startTask(versala3Rampa);
				startTask(seguir);
			}//fim do dist=1

			if(ladoObst == 2)// sem curva de noventa (vira90 direto no obst)

			{

				stopTask(tela);
				stopTask(verdeFalsoD);
				stopTask(verdeFalsoE);
				stopTask(verdD);
				stopTask(verdeE);
				stopTask(seguir);
				stopTask(versala3Inicio);
				stopTask(versala3Rampa);

				motor(esquerda)=0;
				motor(direita)=0;
				sleep(100);




				moveMotorTarget(esquerda, 480, 60);
				moveMotorTarget(direita, 480, -60);
				waitUntilMotorStop(esquerda);
				waitUntilMotorStop(direita);


				while((luzD>=pretoD+5||luzE>=pretoE+5) && graus>-450)
				{

					if(luzD>=pretoD+5&&luzE>=pretoE+5)
					{
						motor(esquerda)=-10;
						motor(direita)=-10;

					}//fim do if td branco

					if(luzD<=pretoD+5)
					{
						motor(direita)=10;
						motor(esquerda)=-10;


					}//fim do preto na direita

					if(luzE<=pretoE+5)
					{
						motor(direita)=-10;
						motor(esquerda)=10;

					}//preto no esq


				}//fim do while de alihamento
				motor(esquerda)=0;
				motor(direita)=0;





				while(distL<15)
				{
					motor[direita]=-51;
					motor[esquerda]=-51;
				}



				motor[direita]=0;
				motor[esquerda]=0;



				moveMotorTarget(direita, 920, -45);
				waitUntilMotorStop(direita);






				while(distL>15)
				{

					motor(esquerda)=-55;
					motor(direita)=-55;
				}

				while(distL<15)
				{
					motor(esquerda)=-40;
					motor(direita)=-40;
				}

				motor(esquerda)=0;
				motor(direita)=0;


				moveMotorTarget(esquerda, 200,-25);
				moveMotorTarget(direita, 200, -25);
				waitUntilMotorStop(esquerda);
				waitUntilMotorStop(direita);


				moveMotorTarget(esquerda, 480, 25);
				moveMotorTarget(direita, 480, -25);
				waitUntilMotorStop(esquerda);
				waitUntilMotorStop(direita);


				moveMotorTarget(esquerda, 500,- 25);
				moveMotorTarget(direita, 500, -25);
				waitUntilMotorStop(esquerda);
				waitUntilMotorStop(direita);



				while(luzE > pretoE+10)
				{
					motor[esquerda]=-25;
					motor[direita]=-25;
				}
				motor[esquerda]=0;
				motor[direita]=0;


				moveMotorTarget(esquerda,250,30);
				moveMotorTarget(direita,250,30);
				waitUntilMotorStop(direita);
				waitUntilMotorStop(esquerda);



				moveMotorTarget(esquerda,480,30);
				moveMotorTarget(direita,480,-30);
				waitUntilMotorStop(direita);
				waitUntilMotorStop(esquerda);


				startTask(verdeFalsoD);
				startTask(verdeFalsoE);
				startTask(verdD);
				startTask(verdE);
				startTask(versala3Rampa);
				startTask(versala3Inicio);
				startTask (seguir);

			}//fim do obst=2






			startTask(verdeFalsoD);
			startTask(verdeFalsoE);
			startTask(verdE);
			startTask(verdD);
			startTask(versala3Inicio);
			startTask(versala3Rampa);
			startTask(seguir);




		}



	}//fin do if

}//fim do while

//fim da task


task verdE()
{
	verdeFalsoL=false;
	startTask(verdeFalsoE);
	while(1)
	{
		if( luzE > verdeE - 15 && luzE < verdeE +15 && GreenE - RedE > 6)
		{	setLEDColor(ledOrange);
			stopTask(obstaculo);
			stopTask(seguir);
			stopTask(verdD);
			stopTask(verdeFalsoD);
			stopTask(verdeFalsoE);
			motor(esquerda)=0;
			motor(direita)=0;
			sleep(500);
			if(luzD > verdeD - 25 && luzD < verdeD +25 && GreenD - RedD > 4)

			{



				moveMotorTarget(direita,150,50);
				moveMotorTarget(esquerda,150,50);
				waitUntilMotorStop(direita);
				waitUntilMotorStop(esquerda);


				moveMotorTarget(direita,750,-50);
				moveMotorTarget(esquerda,750,50);
				waitUntilMotorStop(direita);
				waitUntilMotorStop(esquerda);





				startTask(seguir);
				startTask(obstaculo);
				startTask(verdeFalsoD);
				startTask(verdeFalsoE);
				startTask(verdD);
				setLEDColor(ledGreen);

sleep(100);


			}








			else
			{
				stopTask(obstaculo);
				stopTask(seguir);
				stopTask(verdD);
				stopTask(verdeFalsoD);
				stopTask(verdeFalsoE);
				stopTask(versala3Rampa);
				motor(esquerda)=0;
				motor(direita)=0;
				playSound(soundFastUpwardTones);

				clearTimer(T3);


				motorg(150,30,150,30);

				motorg(330,-30,330,30);

				/*while(time1[T3]<1250)
				{
				motor(esquerda)=30+(luzE-cinzaSE)*kpp;
				motor(direita)=30
				}

				motor[esquerda]=0;
				motor[direita]=0;

				*/

				startTask(seguir);
				startTask(obstaculo);
				startTask(verdeFalsoD);
				startTask(verdeFalsoE);
				startTask(verdD);





			}

		}
	}
}

task verdD()
{
	verdeFalsoR=false;
	startTask(verdeFalsoD);
	while(1)
	{
		if(luzD > verdeD - 15 && luzD < verdeD + 15 && GreenD - RedD > 6)
		{
			setLEDColor(ledOrange);
			stopTask(obstaculo);
			stopTask(seguir);
			stopTask(verdE);
			stopTask(verdeFalsoD);
			stopTask(verdeFalsoE);
			motor(esquerda)=0;
			motor(direita)=0;
			sleep(500);
			if( luzE > verdeE - 25 && luzE < verdeE +25 && GreenE - RedE > 4)

			{



				moveMotorTarget(direita,150,50);
				moveMotorTarget(esquerda,150,50);
				waitUntilMotorStop(direita);
				waitUntilMotorStop(esquerda);



				moveMotorTarget(direita,750,-50);
				moveMotorTarget(esquerda,750,50);
				waitUntilMotorStop(direita);
				waitUntilMotorStop(esquerda);



				startTask(seguir);
				startTask(obstaculo);
				startTask(verdeFalsoD);
				startTask(verdeFalsoE);
				startTask(verdE);
				setLEDColor(ledGreen);

			}

			else
			{
				stopTask(obstaculo);
				stopTask(seguir);
				stopTask(verdE);
				stopTask(verdeFalsoD);
				stopTask(verdeFalsoE);
				stopTask(versala3Inicio);
				motor(esquerda)=0;
				motor(direita)=0;


				clearTimer(T3);

				motorg(150,30,150,30);

				motorg(330,30,330,-30);


				/*
				while(time1[T3]<1250)
				{
				motor(direita)=30+(luzD-cinzaSD)*kpp;
				motor(esquerda)=20;

				}

				motor[esquerda]=0;
				motor[direita]=0;
				*/



				startTask(seguir);
				startTask(obstaculo);
				startTask(verdeFalsoD);
				startTask(verdeFalsoE);
				startTask(verdE);
				startTask(versala3Inicio);

				sleep(100);
			}
		}
	}
}
task verdeFalsoD()

{
	while(1)
	{
		if((luzD<=pretoD) && verdeFalsoR == false )
		{
			clearTimer(T1);
			verdeFalsoR = true;

			while(time1[T1] <=1000 && verdeFalsoR == true)
			{
				if(luzD > verdeD - 15 && luzD < verdeD + 15 && GreenD - RedD > 6)

				{
					stopTask(seguir);
					stopTask(verdD);

					motor(direita)= 0;
					motor(esquerda)=0;

					moveMotorTarget(direita,100,70);
					moveMotorTarget(esquerda,100,70);
					waitUntilMotorStop(direita);
					waitUntilMotorStop(esquerda);

					startTask(seguir);
					startTask(verdD);
					startTask(obstaculo);
					stopTask(verdeFalsoE);

				}//fecha if


			}//fecha while 1

			verdeFalsoR = false;

		}// fecha if


	}

}

task verdeFalsoE()

{
	while(1)
	{
		if((luzE<=pretoE) && verdeFalsoL == false )
		{
			clearTimer(T1);
			verdeFalsoL = true;

			while(time1[T1] <=1000 && verdeFalsoL == true)
			{
				if(luzE > verdeE - 15 && luzE < verdeE + 15 && GreenE - RedE > 6)

				{
					stopTask(seguir);
					stopTask(verdE);

					motor(direita)= 0;
					motor(esquerda)=0;

					moveMotorTarget(direita,100,70);
					moveMotorTarget(esquerda,100,70);
					waitUntilMotorStop(direita);
					waitUntilMotorStop(esquerda);



					startTask(seguir);
					startTask(verdE);


				}


			}
			verdeFalsoL = false;
		}// fecha if


	}
}




task versala3Inicio()
{
	clearTimer(T3);
	if(distL<11)

	{
		while(time1[T3]<2000)
		{
			if(luzD<cinzaD+15 && luzD>cinzaD-15)
			{
				if(luzE<cinzaE+15 && luzE>cinzaE-15)
				{

					startTask(sala3);
					stopTask(seguir);
					stopTask(obstaculo);
					stopTask(verdE);
					stopTask(verdD);
					stopTask(verdeFalsoD);
					stopTask(verdeFalsoE);
				}//fim terceiro if
			}//fecha segundo if
		}//fim do segundo if
	}//fim do while
}//fim da task

///sala3///sala3///sala3///sala3///sala3///sala3///sala3///sala3///sala3///sala3///sala3///sala3///sala3
///sala3///sala3///sala3///sala3///sala3///sala3///sala3///sala3///sala3///sala3///sala3///sala3///sala3///sala3
///sala3///sala3///sala3///sala3///sala3///sala3///sala3///sala3///sala3///sala3///sala3///sala3///sala3///sala3

task sala3()
{
	setLEDColor(ledRedFlash);

	stopTask(versala3Rampa);
	stopTask(seguir);
	stopTask(obstaculo);
	stopTask(verdD);
	stopTask(verdE);
	stopTask(verdeFalsoD);
	stopTask(verdeFalsoE);

	motor(direita)=30;
	motor(esquerda)=30;
	sleep(1500);
	motor(esquerda)=0;
	motor(direita)=0;



	moveMotorTarget(direita,380,-70);
	moveMotorTarget(esquerda,380,70);
	waitUntilMotorStop(esquerda);
	waitUntilMotorStop(direita);

	if(distF<5)
	{
		playSound(nNumbOfSystemSounds);
		moveMotorTarget(direita,300,70);
		moveMotorTarget(esquerda,300,70);
		waitUntilMotorStop(esquerda);
		waitUntilMotorStop(direita);

		motor(direita)=14;
		motor(esquerda)=14;
		sleep(1000);
		motor(esquerda)=0;
		motor(direita)=0;
	}


	if(distF>=5)
	{

		moveMotorTarget(direita,400,70);
		moveMotorTarget(esquerda,400,70);
		waitUntilMotorStop(esquerda);
		waitUntilMotorStop(direita);

		motor(direita)=14;
		motor(esquerda)=14;
		sleep(1000);
		motor(esquerda)=0;
		motor(direita)=0;

	}


	moveMotorTarget(direita,250,-30);
	moveMotorTarget(esquerda,250,-30);
	waitUntilMotorStop(esquerda);
	waitUntilMotorStop(direita);

	moveMotorTarget(direita,380,30);
	moveMotorTarget(esquerda,380,-30);
	waitUntilMotorStop(esquerda);
	waitUntilMotorStop(direita);

	while(distF>3)
	{
		setLEDColor(ledGreen);
		motor(esquerda)=70;
		motor(direita)=70;

	}//fim do while
	motor(esquerda)=0;
	motor(direita)=0;







	if(luzD<pretoD+20)
	{
		sala33=1;

	}//fim do if

	if(sala33==1)
	{
		playSoundFile("Hello");
		setLEDColor(ledOrangePulse);




		moveMotorTarget(direita,200,20);
		moveMotorTarget(esquerda,200,20);
		waitUntilMotorStop(direita);
		waitUntilMotorStop(esquerda);

		motor(esquerda)=10;
		motor(direita)=10;
		sleep(1000);
		motor(esquerda)=0;
		motor(direita)=0;







		setMotorBrakeMode(traz,0);


		moveMotorTarget(direita, 1800,-60);
		moveMotorTarget(esquerda, 1800,-60);
		waitUntilMotorStop(direita);
		waitUntilMotorStop(esquerda);


		setLEDColor(ledGreenPulse);
		playSound(nNumbOfSystemSounds);
		moveMotorTarget(direita,380,-30);
		moveMotorTarget(esquerda,380,30);
		waitUntilMotorStop(direita);
		waitUntilMotorStop(esquerda);

		moveMotorTarget(direita,210,30);
		moveMotorTarget(esquerda,210,30);
		waitUntilMotorStop(direita);
		waitUntilMotorStop(esquerda);



		motor(esquerda)=17;
		motor(direita)=17;
		motor(traz)=100;
		sleep(1200);
		motor(esquerda)=0;
		motor(direita)=0;
		motor(traz)=0;
		setMotorBrakeMode(traz,0);

		moveMotorTarget(direita, 800,-42);
		moveMotorTarget(esquerda, 800,-42);
		waitUntilMotorStop(direita);
		waitUntilMotorStop(esquerda);

		motorg(10,60,10,-60);

		motorg(1500,-42,1500,-42);

		motor(esquerda)=-13;
		motor(direita)=-13;
		motor(traz)=100;
		sleep(1000);
		motor(traz)=0;
		motor(esquerda)=0;
		motor(direita)=0;


		moveMotorTarget(esquerda,50,50);
		moveMotorTarget(direita,50,50);
		waitUntilMotorStop(esquerda);
		waitUntilMotorStop(direita);




		moveMotorTarget(direita,420,-50);
		moveMotorTarget(esquerda,420,50);
		waitUntilMotorStop(direita);
		waitUntilMotorStop(esquerda);



		moveMotorTarget(direita, 680,-50);
		moveMotorTarget(esquerda, 680,-50);
		waitUntilMotorStop(direita);
		waitUntilMotorStop(esquerda);






		moveMotorTarget(direita,420,-50);
		moveMotorTarget(esquerda,420,50);
		waitUntilMotorStop(direita);
		waitUntilMotorStop(esquerda);

		moveMotorTarget(direita,480,70);
		moveMotorTarget(esquerda,480,70);
		waitUntilMotorStop(direita);
		waitUntilMotorStop(esquerda);


		playTone(1000,1000);
		motor(esquerda)=17;
		motor(direita)=17;
		sleep(1000);
		motor(esquerda)=0;
		motor(direita)=0;




		moveMotorTarget(direita, 1000,-42);
		moveMotorTarget(esquerda, 1000,-42);
		waitUntilMotorStop(direita);
		waitUntilMotorStop(esquerda);


		moveMotorTarget(direita, 5,-47);
		moveMotorTarget(esquerda, 5,47);
		waitUntilMotorStop(direita);
		waitUntilMotorStop(esquerda);


		moveMotorTarget(direita, 1250,-42);
		moveMotorTarget(esquerda, 1250,-42);
		waitUntilMotorStop(direita);
		waitUntilMotorStop(esquerda);


		motor(esquerda)=-10;
		motor(direita)=-10;
		sleep(1000);
		motor(esquerda)=0;
		motor(direita)=0;

		moveMotorTarget(esquerda,100,70);
		moveMotorTarget(direita,100,70);
		waitUntilMotorStop(esquerda);
		waitUntilMotorStop(direita);

		moveMotorTarget(direita,420,60);
		moveMotorTarget(esquerda,420,-60);
		waitUntilMotorStop(direita);
		waitUntilMotorStop(esquerda);

		moveMotorTarget(direita,100,-60);
		moveMotorTarget(esquerda,100,-60);
		waitUntilMotorStop(direita);
		waitUntilMotorStop(esquerda);



		moveMotorTarget(direita,30,-60);
		moveMotorTarget(esquerda,30,60);
		waitUntilMotorStop(direita);
		waitUntilMotorStop(esquerda);



		moveMotorTarget(direita,250,-60);
		moveMotorTarget(esquerda,250,-60);
		waitUntilMotorStop(direita);
		waitUntilMotorStop(esquerda);


		motor(traz)=-100;
		sleep(500);
		motor(direita)=30;
		motor(esquerda)=30;

		motor(traz)=-100;
		sleep(3000);
		motor(esquerda)=0;
		motor(direita)=0;
		motor(traz)=100;
		sleep(600);
		motor(traz)=0;
		playImmediateTone(10,200);
		setMotorBrakeMode(traz,0);




		/////termina primeira varredura patamar posição 1



		motorg(300,-50,300,-50);


		motorg(380,40,380,-40);
		//playImmediateTone(3000,3000);
		//motor(traz)=100;
		/////playSound(soundBeepBeep);
		motorg(200,-50,200,-50);


		motor(esquerda)=-10;
		motor(direita)=-10;
		sleep(1200);
		motor(traz)=-100;
		motor(esquerda)=0;
		motor(direita)=0;
		motor(traz)=0;
		motorg(60,30,60,30);

		motorg(320,-30,320,-30);







		motorg(100,40,100,50);

		motorg(400,40,400,-50);

		/////	playSound(soundUpwardTones);


		motorg(100,60,100,60);

		motorg(80,-50,80,50);
		////// playTone(10000,1000);
		//motor(traz)=70;

		motorg(1300,-80,1300,-80);


		motorg(430,40,430,-40);

		//motorg(1420,-50,1420,-50);
		motor[esquerda]=-50;
		motor[direita]=-50;
		sleep(4800);
		motor[esquerda]=0;
		motor[direita]=0;

		motorg(430,50,430,-50);

		//motorg(430,40,430,-40);

		motor[esquerda]=-47;
		motor[direita]=-47;
		sleep(4200);
		motor[esquerda]=0;
		motor[direita]=0;
		motorg(430,40,430,-40);

		//	motor[esquerda]=-50;
		//	motor[direita]=-50;
		//if(luzD<= pretoD + 10);
		//		{
		//motor[esquerda]=0;
		//	motor[direita]=0;

		//	}
		motor[esquerda]=-47;
		motor[direita]=-47;
		sleep(3500);//
		motor[esquerda]=0;
		motor[direita]=0;


		motorg(200,-40,200,40);

		//	moveMotorTarget(traz,

		motor(traz)=-100;
		sleep(1500);
		motor(esquerda)=30;
		motor(direita)=30;
		sleep(4000);
		motor(traz)=0;

		motorg(100,50,100,50);

	}//fim do if

	if(sala33==0)
	{
		setLEDColor(ledRedPulse);
		playTone(100,100);



		moveMotorTarget(direita,250,70);
		moveMotorTarget(esquerda,250,70);
		waitUntilMotorStop(direita);
		waitUntilMotorStop(esquerda);

		motor(esquerda)=10;
		motor(direita)=10;
		sleep(1500);
		motor(esquerda)=0;
		motor(direita)=0;

		moveMotorTarget(direita,90,-50);
		moveMotorTarget(esquerda,90,-50);
		waitUntilMotorStop(direita);
		waitUntilMotorStop(esquerda);


		moveMotorTarget(direita,480,50);
		moveMotorTarget(esquerda,480,-50);
		waitUntilMotorStop(direita);
		waitUntilMotorStop(esquerda);



		moveMotorTarget(direita,400,-50);
		moveMotorTarget(esquerda,400,-50);
		waitUntilMotorStop(esquerda);
		waitUntilMotorStop(direita);

		motor(esquerda)=70;
		motor(direita)=70;
		sleep(2000);
		motorg(15,-30,15,30);


		while(distF>=3)
		{
			motor(direita)=70;
			motor(esquerda)=70;

		}//fim do while
		motor(esquerda)=0;
		motor(direita)=0;



		if(luzD<30)
		{

			sala33=2;
		}//fim do while

		else sala33 =3;

		if(sala33==2)
		{
			playSound(nNumbOfSystemSounds);
			setLEDColor(ledGreenFlash);

			moveMotorTarget(direita,270,50);
			moveMotorTarget(esquerda,270,50);
			waitUntilMotorStop(direita);
			waitUntilMotorStop(esquerda);


			motor(esquerda)=7;
			motor(direita)=7;
			sleep(1200);
			motor(esquerda)=0;
			motor(direita)=0;




			moveMotorTarget(direita,1200,-50);
			moveMotorTarget(esquerda,1200,-50);
			waitUntilMotorStop(esquerda);
			waitUntilMotorStop(direita);


			motorg(400,30,400,-30);


			/*moveMotorTarget(direita,163,-30);
			moveMotorTarget(esquerda,163,30);
			waitUntilMotorStop(direita);
			waitUntilMotorStop(esquerda);

			moveMotorTarget(direita,350,-50);
			moveMotorTarget(esquerda,350,-50);
			waitUntilMotorStop(esquerda);
			waitUntilMotorStop(direita);

			moveMotorTarget(direita,245,-30);
			moveMotorTarget(esquerda,246,30);
			waitUntilMotorStop(direita);
			waitUntilMotorStop(esquerda);
			*/
			moveMotorTarget(direita,380,50);
			moveMotorTarget(esquerda,380,50);
			waitUntilMotorStop(direita);
			waitUntilMotorStop(esquerda);






			motor[direita]=10;
			motor(traz)=100;

			motor[esquerda]=10;
			sleep(2000);

			motor[direita]=0;

			motor[esquerda]=0;

			motor(traz)=0;




			setMotorBrakeMode(traz,1);


			moveMotorTarget(direita,2300,-42);
			moveMotorTarget(esquerda,2300,-42);
			waitUntilMotorStop(direita);
			waitUntilMotorStop(esquerda);

			playSound(nNumbOfSystemSounds);


			setMotorBrakeMode(traz,1);

			motor(esquerda)=-10;
			motor(direita)=-10;
			sleep(1500);
			motor(esquerda)=0;
			motor(direita)=0;



			moveMotorTarget(direita,500,50);
			moveMotorTarget(esquerda,500,-50);
			waitUntilMotorStop(direita);
			waitUntilMotorStop(esquerda);

			moveMotorTarget(direita,530,-50);
			moveMotorTarget(esquerda,530,-50);
			waitUntilMotorStop(direita);
			waitUntilMotorStop(esquerda);

			moveMotorTarget(direita,520,50);
			moveMotorTarget(esquerda,520,-50);
			waitUntilMotorStop(direita);
			waitUntilMotorStop(esquerda);///////////



			moveMotorTarget(direita,700,50);
			moveMotorTarget(esquerda,700,50);
			waitUntilMotorStop(direita);
			waitUntilMotorStop(esquerda);

			motor(esquerda)=10;
			motor(direita)=10;
			sleep(2000);
			motor(esquerda)=0;
			motor(direita)=0;


			moveMotorTarget(direita,2300,-42);
			moveMotorTarget(esquerda,2300,-42);
			waitUntilMotorStop(direita);
			waitUntilMotorStop(esquerda);




			motor(esquerda)=-10;
			motor(direita)=-10;
			sleep(2000);
			motor(esquerda)=0;
			motor(direita)=0;

			moveMotorTarget(direita,150,10);
			moveMotorTarget(esquerda,150,10);
			waitUntilMotorStop(direita);
			waitUntilMotorStop(esquerda);

			moveMotorTarget(direita,480,50);
			moveMotorTarget(esquerda,480,-50);
			waitUntilMotorStop(direita);
			waitUntilMotorStop(esquerda);

			moveMotorTarget(direita,1100,-42);
			moveMotorTarget(esquerda,1100,-42);
			waitUntilMotorStop(direita);
			waitUntilMotorStop(esquerda);
			playSound(soundBeepBeep);

			moveMotorTarget(direita,140,-50);
			moveMotorTarget(esquerda,140,50);
			waitUntilMotorStop(direita);
			waitUntilMotorStop(esquerda);

			moveMotorTarget(direita,60,-50);
			moveMotorTarget(esquerda,60,-50);
			waitUntilMotorStop(direita);
			waitUntilMotorStop(esquerda);



			playSound(soundDownwardTones);

			motor(traz)=-100;
			sleep(2000);
			motor(traz)=-100;
			motor(esquerda)=30;
			motor(direita)=30;
			sleep(2000);
			motor(esquerda)=0;
			motor(direita)=0;

			setMotorBrakeMode(traz,0);
			playImmediateTone(100,100);
			///////fim primeira varredura patamar 2//////

			motorg(300,-50,300,50);

			motorg(1800,-50,1800,-50);

			motorg(10,10,10,10);

			motorg(20,30,20,30);


			motorg(390,-40,390,40);
			motor(traz)=100;
			sleep(1500);



			motorg(1000,-50,1000,-50);
			motor(esquerda)=-10;
			motor(direita)=-10;
			sleep(1500);
			motor(esquerda)=0;
			motor(direita)=0;
			motor(traz)=0;
			motorg(10,10,10,10);


			motorg(480,-50,480,50);


			motorg(2100,-50,2100,-50);

			motor(esquerda)=-10;
			motor(direita)=-10;
			sleep(1500);
			motor(esquerda)=0;
			motor(direita)=0;

			motorg(10,10,10,10);

			motorg(480,-50,480,50);

			motor(traz)=100;
			motorg(1800,-50,1800,-50);

			motor(esquerda)=-10;
			motor(direita)=-10;
			sleep(1500);
			motor(esquerda)=0;
			motor(direita)=0;

			motorg(10,10,10,10);

			motorg(480,-50,480,50);


motorg(1400,-50,1400,-50);


motorg(200,50,200,-50);

motorg(90,-50,90,-50);



	motor(traz)=-100;
			sleep(2000);
			motor(traz)=-100;
			motor(esquerda)=30;
			motor(direita)=30;
			sleep(2000);
			motor(esquerda)=0;
			motor(direita)=0;
sleep(100000000);

		}

		//final2//

		if(sala33==3)
		{

			playSound(nNumbOfSystemSounds);
			setLEDColor(ledGreenFlash);

			moveMotorTarget(direita,270,50);
			moveMotorTarget(esquerda,270,50);
			waitUntilMotorStop(direita);
			waitUntilMotorStop(esquerda);


			motor(esquerda)=7;
			motor(direita)=7;
			sleep(1200);
			motor(esquerda)=0;
			motor(direita)=0;




			moveMotorTarget(direita,1200,-50);
			moveMotorTarget(esquerda,1200,-50);
			waitUntilMotorStop(esquerda);
			waitUntilMotorStop(direita);


			motorg(400,30,400,-30);


			/*moveMotorTarget(direita,163,-30);
			moveMotorTarget(esquerda,163,30);
			waitUntilMotorStop(direita);
			waitUntilMotorStop(esquerda);

			moveMotorTarget(direita,350,-50);
			moveMotorTarget(esquerda,350,-50);
			waitUntilMotorStop(esquerda);
			waitUntilMotorStop(direita);

			moveMotorTarget(direita,245,-30);
			moveMotorTarget(esquerda,246,30);
			waitUntilMotorStop(direita);
			waitUntilMotorStop(esquerda);
			*/
			moveMotorTarget(direita,380,50);
			moveMotorTarget(esquerda,380,50);
			waitUntilMotorStop(direita);
			waitUntilMotorStop(esquerda);






			motor[direita]=10;
			motor(traz)=100;

			motor[esquerda]=10;
			sleep(2000);

			motor[direita]=0;

			motor[esquerda]=0;

			motor(traz)=0;




			setMotorBrakeMode(traz,1);


			moveMotorTarget(direita,2300,-42);
			moveMotorTarget(esquerda,2300,-42);
			waitUntilMotorStop(direita);
			waitUntilMotorStop(esquerda);

			playSound(nNumbOfSystemSounds);


			setMotorBrakeMode(traz,1);

			motor(esquerda)=-10;
			motor(direita)=-10;
			sleep(1500);
			motor(esquerda)=0;
			motor(direita)=0;
playSound(nNumbOfSystemSounds);


			moveMotorTarget(direita,500,50);
			moveMotorTarget(esquerda,500,-50);
			waitUntilMotorStop(direita);
			waitUntilMotorStop(esquerda);

			moveMotorTarget(direita,530,-50);
			moveMotorTarget(esquerda,530,-50);
			waitUntilMotorStop(direita);
			waitUntilMotorStop(esquerda);

			moveMotorTarget(direita,520,50);
			moveMotorTarget(esquerda,520,-50);
			waitUntilMotorStop(direita);
			waitUntilMotorStop(esquerda);///////////



			moveMotorTarget(direita,700,50);
			moveMotorTarget(esquerda,700,50);
			waitUntilMotorStop(direita);
			waitUntilMotorStop(esquerda);

			motor(esquerda)=10;
			motor(direita)=10;
			sleep(2000);
			motor(esquerda)=0;
			motor(direita)=0;


			moveMotorTarget(direita,500,-42);
			moveMotorTarget(esquerda,500,-42);
			waitUntilMotorStop(direita);
			waitUntilMotorStop(esquerda);

motorg(20,-50,20,50);

motorg(1700,-42,1700,-42);




motor(traz)=100;
			motor(esquerda)=-7;
			motor(direita)=-7;
			sleep(2000);
			motor(esquerda)=0;
			motor(direita)=0;
motor(traz)=0;

			moveMotorTarget(direita,50,10);
			moveMotorTarget(esquerda,50,10);
			waitUntilMotorStop(direita);
			waitUntilMotorStop(esquerda);

			moveMotorTarget(direita,480,-50);
			moveMotorTarget(esquerda,480,50);
			waitUntilMotorStop(direita);
			waitUntilMotorStop(esquerda);



			moveMotorTarget(direita,1700,50);
			moveMotorTarget(esquerda,1700,50);
			waitUntilMotorStop(direita);
			waitUntilMotorStop(esquerda);
			playSound(soundBeepBeep);

			motor(esquerda)=10;
			motor(direita)=10;
			sleep(500);
			motor(esquerda)=0;
			motor(direita)=0;
			motor(traz)=0;



		motorg(20,50,20,50);

		motorg(480,50,480,-50);

motorg(450,40,450,40);

motor(esquerda)=10;
			motor(direita)=10;
			sleep(1200);
			motor(esquerda)=0;
			motor(direita)=0;


			motorg(1500,-50,1500,-50);



			playSound(soundDownwardTones);



			setMotorBrakeMode(traz,0);
			playImmediateTone(100,100);
			///////fim primeira varredura patamar 3//////

motorg(530,-50,530,-50);

	motor(traz)=-100;

			sleep(2000);

			motor(traz)=0;

			motorg(100,50,100,50);

			playTone(999,999);
				motorg(400,-50,400,50);

					motor(traz)=-100;

			sleep(2000);

			motor(traz)=0;

					motor(traz)=100;

			sleep(2000);

			motor(traz)=0;




					motor[esquerda]=-50;
		motor[direita]=-50;
		sleep(4200);
		motor[esquerda]=0;
		motor[direita]=0;
		motorg(430,-60,430,60);


	motor[esquerda]=-50;
		motor[direita]=-50;
		sleep(1900);
		motor[esquerda]=0;
		motor[direita]=0;
		motorg(430,-60,430,60);


				motor[esquerda]=-50;
		motor[direita]=-50;
		sleep(4200);
		motor[esquerda]=0;
		motor[direita]=0;
		motorg(430,-60,430,60);

			motor[esquerda]=-50;
		motor[direita]=-50;
		sleep(4200);
		motor[esquerda]=0;
		motor[direita]=0;

playTone(555,555);//teste
sleep(100);//teste
	motor(traz)=-100;
			sleep(1000);




			sleep(200);//teste

motor(traz)=100;
				motor[esquerda]=50;
		motor[direita]=50;
		sleep(5000);
		motor[esquerda]=0;
		motor[direita]=0;

motor(traz)=0;

		}


	}//fim do if


}//fim da task

//taskRAmpa//taskRAmpa//taskRAmpa//taskRAmpa//taskRAmpa//taskRAmpa//taskRAmpa//taskRAmpa//taskRAmpa//taskRAmpa//taskRAmpa
//taskRAmpa//taskRAmpa//taskRAmpa//taskRAmpa//taskRAmpa//taskRAmpa//taskRAmpa//taskRAmpa//taskRAmpa//taskRAmpa//taskRAmpa
//taskRAmpa//taskRAmpa//taskRAmpa//taskRAmpa//taskRAmpa//taskRAmpa//taskRAmpa//taskRAmpa//taskRAmpa//taskRAmpa//taskRAmpa
//taskRAmpa//taskRAmpa//taskRAmpa//taskRAmpa//taskRAmpa//taskRAmpa//taskRAmpa//taskRAmpa//taskRAmpa//taskRAmpa//taskRAmpa

task versala3Rampa()
{
	while(1)
	{
		if(distL<11)
		{
			rampa3=true;
			clearTimer(T4);
			while(time1[T4]<5000 && rampa3==true)
			{
				setLEDColor(ledOrange);
				if(distL>=13)
				{
					rampa3=false;
				}
			}//fim do while
			setLEDColor(ledGreen);
			if(rampa3==true)
			{
				Fmin=70;
				kp=1.3;
				while(1)
				{
					if(distL>17)
					{
						sleep(100);
						startTask(sala3);
						stopTask(seguir);
						stopTask(obstaculo);
						stopTask(verdE);
						stopTask(verdD);
						stopTask(verdeFalsoD);
						stopTask(verdeFalsoE);
						wait1Msec(100);
					}//fim do if
				}
			}//fim do if
		}//fim do primeiro if
	}//fim do while

}//fim da task
