#pragma config(Sensor, S1,     corD,           sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S2,     corE,           sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S3,     ultraF,         sensorEV3_Ultrasonic)
#pragma config(Sensor, S4,     ultraL,         sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          garra,         tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          esq,           tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          dir,           tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int caso = 0;
int PretoE = 56;
int PretoD = 57;
int BrancoE = 352;
int BrancoD = 281;
int VerdeE = 36;
int VerdeD = 33;
int VerdeDF = 25;
int VerdeEF = 24;
int Fmin= 30;
int Curva90 = 455;
int Curva180 = 930;
int CurvaBeco = 870;
int curvaVerde = 400;
int LadoObst = 0;
// 0 = dir e 1 = esq
float kp = 1.5, kd = 15;
task OBSTACULO1();
task OBSTACULO2();
task seguir();
task sensores();
task tela();
task VerdeT();
task VerdefakeE();
task VerdefakeD();
task verSala3();
task sala3();
int VnE, VnD, LuzE, LuzD, Erro, lastErro, FE, FD, distF,distL,patamar, EncoderDir;
long redD , redE, greenE, greenD, blueD,blueE;
bool VerdeFalsoE = false, VerdeFalsoD = false , controle1,controle2;
task main()
{//ITM
	motor[garra] = -80;
	sleep(1500);
	motor[garra] = 0;
	setMotorBrakeMode(garra,0);

	startTask (sensores);
	startTask (tela);
	while(1)
	{//IW
		if(getButtonPress(buttonEnter))
		{
			startTask(seguir);
			startTask (OBSTACULO1);
			startTask (OBSTACULO2);
			startTask (VerdeT);
			startTask(VerdefakeE);
			startTask(VerdefakeD);
			startTask(verSala3);

		}
		sleep(10);
	}//FW
}//FTM

task sensores()
{//ITSensores

	while(1)
	{//IW
		LuzE = SensorValue[corE];
		LuzD = SensorValue[corD];
		distF= SensorValue[ultraF];
		distL = SensorValue[ultraL];
		getColorRGB(corE ,redE , greenE, blueE);
		getColorRGB(corD ,redD , greenD, blueD);

		EncoderDir = 	getMotorEncoder(dir);
		sleep(10);

	}//FW
}//FTSensores

task tela()
{//ITTela
	while(1)
	{//IW
		displayBigTextLine(2,"SensorE: %d",LuzE);
		displayBigTextLine(4,"SensorD: %d",LuzD);
		displayBigTextLine(6,"DISTANCIA: %d",distF);
		displayBigTextLine(8,"DISTANCIAL: %d",distL);

		sleep(500);
	}//FW
}//FTTela

task seguir() //segue linHA
{//ITSeguir
	while(1)
	{//IW
		VnE = (100*(LuzE - PretoE))/(BrancoE - PretoE);
		VnD = (100*(LuzD - PretoD))/(BrancoD - PretoD);
		if(VnD > 100) VnD = 100;
		if(VnD < -100) VnD = -100;
		if(VnE > 100) VnE= 100;
		if(VnE < -100) VnE = -100;

		Erro = VnD - VnE;

		FE=Fmin+(kp*Erro)+kd*(Erro-lastErro);
		FD=Fmin-(kp*Erro)-kd*(Erro-lastErro);

		lastErro = Erro;

		motor[esq] = FE;
		motor[dir] = FD;

		sleep(10);
	}//Fw
}//FTSeguir

task OBSTACULO1 ()//arrumar graus
{//ITOBS
	while(1)
	{//IW
		if (LadoObst == 0)
		{//Iif = 0
			if (distF < 6)
			{//Iif1
				stopTask(verSala3);
				stopTask (VerdefakeD);
				stopTask (VerdefakeE);
				stopTask (VerdeT);
				stopTask (seguir);
				motor	[esq]= 0;
				motor	[dir]= 0;

				displayBigTextLine(10,"VnE: %d",VnE);
				displayBigTextLine(12,"VnD: %d",VnD);
				sleep(2500);

				moveMotorTarget(dir,100,-40);//1 passo
				moveMotorTarget(esq,100,-40);//
				waitUntilMotorStop(esq);//
				waitUntilMotorStop(dir);//

				if(VnE < 85)
				{
					moveMotorTarget(dir,115,-40);//1 passo
					moveMotorTarget(esq,115,40);//
					waitUntilMotorStop(esq);//
					waitUntilMotorStop(dir);//
				}

				if(VnD < 90)
				{
					moveMotorTarget(dir,115,40);//1 passo
					moveMotorTarget(esq,115,-40);//
					waitUntilMotorStop(esq);//
					waitUntilMotorStop(dir);//
				}


				moveMotorTarget(dir,Curva90,40);//1 passo
				moveMotorTarget(esq,Curva90,-40);//
				waitUntilMotorStop(esq);//
				waitUntilMotorStop(dir);//

				motor[esq] = 0;
				motor[dir] = 0;

				while(distL <  15)
				{
					motor[dir] = 40;//2 passo
					motor[esq] = 40;//
				}
				moveMotorTarget(dir,450,40);//
				moveMotorTarget(esq,450,40);//
				waitUntilMotorStop(dir);//
				waitUntilMotorStop(esq);//

				moveMotorTarget(dir,Curva90,-40);//3 passo
				moveMotorTarget(esq,Curva90,40);//
				waitUntilMotorStop(esq);//
				waitUntilMotorStop(dir);//

				while(distL > 15)
				{
					motor[dir]=40;
					motor[esq]=40;
				}

				while(distL  < 15)
				{
					motor[esq]=40;
					motor[dir]=40;
				}
				motor[esq]=0;
				motor[dir]=0;


			resetMotorEncoder(dir);
				sleep(150);
				while( EncoderDir < 500 && LuzD > PretoD + 5 && LuzE > PretoE + 5)
				{
					motor[dir] = 40;
					motor[esq] = 40;
				}
				motor[dir] = 0;//2 passo
				motor[esq] = 0;


				if ( EncoderDir < 500 )
				{

					moveMotorTarget(dir,200,40);// passo
					moveMotorTarget(esq,200,40);//
					waitUntilMotorStop(esq);//
					waitUntilMotorStop(dir);//

					moveMotorTarget(dir,Curva90,40);//5 passof
					moveMotorTarget(esq,Curva90,-40);//
					waitUntilMotorStop(esq);//
					waitUntilMotorStop(dir);//


				}
				else
				{
					moveMotorTarget(dir,300,-40);// passo
					moveMotorTarget(esq,300,-40);//
					waitUntilMotorStop(esq);//
					waitUntilMotorStop(dir);//

					moveMotorTarget(dir,Curva90,40);//5 passof
					moveMotorTarget(esq,Curva90,-40);//
					waitUntilMotorStop(esq);//
					waitUntilMotorStop(dir);//
				}
				moveMotorTarget(dir,Curva90,-40);//
				moveMotorTarget(esq,Curva90,40);//
				waitUntilMotorStop(esq);//
				waitUntilMotorStop(dir);//

				while(LuzE > PretoE + 10)
				{
					motor[dir] = 30;
					motor[esq] = 30;
				}
				motor[dir] = 0;
				motor[esq] = 0;

				moveMotorTarget(dir,200,40);//
				moveMotorTarget(esq,200,40);//
				waitUntilMotorStop(dir);//
				waitUntilMotorStop(esq);//

				moveMotorTarget(dir,Curva90,-40);//
				moveMotorTarget(esq,Curva90,40);//
				waitUntilMotorStop(esq);//
				waitUntilMotorStop(dir);//

				while(distF > 3)
				{
					startTask(seguir);
					Fmin = 20;
					kp = 1.8;
				}
				stopTask(seguir);
				Fmin = 40;
				kp = 1.5;

				motor[dir]=0;
				motor[esq]=0;

				resetMotorEncoder(dir);
				sleep(150);
				while(EncoderDir > -550)
				{
					motor[dir]= -25;
					motor[esq]= -25;
					if(LuzE < PretoE + 5 && caso != 3 && caso != 4 && caso != 6)
					{
						playTone(130,130);
						caso = 1;
					}
					if(LuzD < PretoD + 5 && caso != 3 && caso != 4 && caso != 6)
					{
						playTone(100,100);
						caso = 2;
					}
					if(LuzE > VerdeE - 10 && LuzE < VerdeE + 10 && greenE - redE > 8 && caso != 5)/////Verde esquerdo
					{
						playTone(40,40);
						caso = 3;
					}
					if(LuzD > VerdeD - 10 && LuzD < VerdeD + 10 && greenD - redD > 8 && caso != 5)//////verde direito
					{
						playTone(70,70);
						caso = 4;
					}
					if(LuzE > VerdeE - 10 && LuzE < VerdeE + 10 && LuzD > VerdeD - 10 && LuzD < VerdeD + 10 && greenE - redE > 8 && greenD - redD > 8 )////beco
					{
						playTone(10,10);
						caso = 5;
					}
					if(LuzD < PretoD + 5 && LuzE < PretoE + 5 && caso != 3 && caso != 4 && caso != 5)////encruzilhada
					{
						playTone(10,10);
						caso = 6;


					}
				}
				motor[dir] = 0;
				motor[esq] = 0;

				if(caso == 0)//////linha reta
				{
					moveMotorTarget(dir,Curva180,-40);// passo
					moveMotorTarget(esq,Curva180,40);//
					waitUntilMotorStop(esq);//
					waitUntilMotorStop(dir);//
				}
				if(caso == 1)/////preto esquerdo
				{
					while(LuzE > PretoE + 10)
					{
						motor[dir]= 25;
						motor[esq]= 25;
					}
					moveMotorTarget(dir,200,40);// passo
					moveMotorTarget(esq,200,40);//
					waitUntilMotorStop(esq);//
					waitUntilMotorStop(dir);//


					moveMotorTarget(dir,Curva90,-40);// passo
					moveMotorTarget(esq,Curva90,40);//
					waitUntilMotorStop(esq);//
					waitUntilMotorStop(dir);//

					while(LuzD > PretoD + 10)
					{
						motor[dir]= -25;
						motor[esq]= -25;
					}
					if(LuzE < PretoE + 10)
					{
					 moveMotorTarget(dir,190,40);// passo
						moveMotorTarget(esq,190,40);//
						waitUntilMotorStop(esq);//
						waitUntilMotorStop(dir);//

						moveMotorTarget(dir,Curva90,40);// passo
						moveMotorTarget(esq,Curva90,-40);//
						waitUntilMotorStop(esq);//
						waitUntilMotorStop(dir);//

						moveMotorTarget(dir,200,-40);// passo
						moveMotorTarget(esq,200,-40);//
						waitUntilMotorStop(esq);//
						waitUntilMotorStop(dir);//

						moveMotorTarget(dir,CurvaBeco,40);// passo
						moveMotorTarget(esq,CurvaBeco,-40);//
						waitUntilMotorStop(esq);//
						waitUntilMotorStop(dir);//
					}
					else
					{

						moveMotorTarget(dir,200,40);// passo
						moveMotorTarget(esq,200,40);//
						waitUntilMotorStop(esq);//
						waitUntilMotorStop(dir);//
					}
				}

				if(caso == 2)////preto direito
				{
					while(LuzD > PretoD + 10)
					{
						motor[dir]= 25;
						motor[esq]= 25;
					}
					moveMotorTarget(dir,200,40);// passo
					moveMotorTarget(esq,200,40);//
					waitUntilMotorStop(esq);//
					waitUntilMotorStop(dir);//


					moveMotorTarget(dir,Curva90,40);// passo
					moveMotorTarget(esq,Curva90,-40);//
					waitUntilMotorStop(esq);//
					waitUntilMotorStop(dir);//

					while(LuzE > PretoE + 10)
					{
						motor[dir]= -25;
						motor[esq]= -25;
					}
					if(LuzD < PretoD + 10)
					{
						moveMotorTarget(dir,Curva90,-40);// passo
						moveMotorTarget(esq,Curva90,40);//
						waitUntilMotorStop(esq);//
						waitUntilMotorStop(dir);//

						moveMotorTarget(dir,200,-40);// passo
						moveMotorTarget(esq,200,-40);//
						waitUntilMotorStop(esq);//
						waitUntilMotorStop(dir);//

						moveMotorTarget(dir,CurvaBeco,40);// passo
						moveMotorTarget(esq,CurvaBeco,-40);//
						waitUntilMotorStop(esq);//
						waitUntilMotorStop(dir);//
					}
					else
					{

						moveMotorTarget(dir,200,40);// passo
						moveMotorTarget(esq,200,40);//
						waitUntilMotorStop(esq);//
						waitUntilMotorStop(dir);//
					}

				}
				if(caso == 3)/////verde esquerdo
				{
					while(LuzE > PretoE + 10)
					{
						motor[dir]= 25;
						motor[esq]= 25;
					}
					moveMotorTarget(dir,200,40);// passo
					moveMotorTarget(esq,200,40);//
					waitUntilMotorStop(esq);//
					waitUntilMotorStop(dir);//


					moveMotorTarget(dir,Curva90,-40);// passo
					moveMotorTarget(esq,Curva90,40);//
					waitUntilMotorStop(esq);//
					waitUntilMotorStop(dir);//

					moveMotorTarget(dir,150,-40);// passo
					moveMotorTarget(esq,150,-40);//
					waitUntilMotorStop(esq);//
					waitUntilMotorStop(dir);//
				}
				if(caso == 4)////verde direito
				{
					while(LuzD > PretoD + 10)
					{
						motor[dir]= 25;
						motor[esq]= 25;
					}
					moveMotorTarget(dir,200,40);// passo
					moveMotorTarget(esq,200,40);//
					waitUntilMotorStop(esq);//
					waitUntilMotorStop(dir);//


					moveMotorTarget(dir,Curva90,40);// passo
					moveMotorTarget(esq,Curva90,-40);//
					waitUntilMotorStop(esq);//
					waitUntilMotorStop(dir);//

					moveMotorTarget(dir,100,40);// passo
					moveMotorTarget(esq,100,40);//
					waitUntilMotorStop(esq);//
					waitUntilMotorStop(dir);//
				}
				if(caso == 5)//beco
				{
					while(LuzE > PretoE + 10 && LuzD > PretoD + 10)
					{
						motor[dir]= 30;
						motor[esq]= 30;
					}
					moveMotorTarget(dir,150,40);// passo
					moveMotorTarget(esq,150,40);//
					waitUntilMotorStop(esq);//
					waitUntilMotorStop(dir);//
				}
				if(caso == 6)
				{
					moveMotorTarget(dir,Curva180,-40);// passo
					moveMotorTarget(esq,Curva180,40);//
					waitUntilMotorStop(esq);//
					waitUntilMotorStop(dir);//
				}
				startTask (VerdefakeD);
				startTask (VerdefakeE);
				startTask (VerdeT);
				startTask (seguir);//
			}//Fif distF
		}//Fif = 0
	}//FW
}//FTOBST 1
task OBSTACULO2 ()
{//ITOBST2
	while(1)
	{
		if (LadoObst == 1)/////////////////////////////////////////////////////////LADO 1/////////////////////////////////////////
		{//Iif = 1
			if (distF < 6)
			{//Iif2
				stopTask(verSala3);
				stopTask (VerdefakeD);
				stopTask (VerdefakeE);
				stopTask (VerdeT);
				stopTask (seguir);
				motor	[esq]= 0;
				motor	[dir]= 0;

				moveMotorTarget(dir,100,-40);//1 passo
				moveMotorTarget(esq,100,-40);//
				waitUntilMotorStop(esq);//
				waitUntilMotorStop(dir);//


				if(VnE < 85)
				{
					moveMotorTarget(dir,115,-40);//1 passo
					moveMotorTarget(esq,115,40);//
					waitUntilMotorStop(esq);//
					waitUntilMotorStop(dir);//
				}

				if(VnD < 90)
				{
					moveMotorTarget(dir,100,40);//1 passo
					moveMotorTarget(esq,100,-40);//
					waitUntilMotorStop(esq);//
					waitUntilMotorStop(dir);//
				}

				moveMotorTarget(dir,Curva90,40);//1 passo
				moveMotorTarget(esq,Curva90,-40);//
				waitUntilMotorStop(esq);//
				waitUntilMotorStop(dir);//

				motor[esq] = 0;
				motor[dir] = 0;

				while(distL <  6)
				{
					motor[dir] = -40;//2 passo
					motor[esq] = -40;//
				}

				moveMotorTarget(dir,340,-40);//
				moveMotorTarget(esq,340,-40);//
				waitUntilMotorStop(dir);//
				waitUntilMotorStop(esq);//

				moveMotorTarget(dir,Curva90,40);//3 passo
				moveMotorTarget(esq,Curva90,-40);//
				waitUntilMotorStop(esq);//
				waitUntilMotorStop(dir);//

				while(distL >  15)
				{
					motor[dir] = -40;//2 passo
					motor[esq] = -40;//
				}

				while(distL <  15)
				{
					motor[dir] = -40;//2 passo
					motor[esq] = -40;//
				}
				motor[dir] = 0;//2 passo
				motor[esq] = 0;

				resetMotorEncoder(dir);
				sleep(150);
				while( EncoderDir > -500 && LuzD > PretoD + 5 && LuzE > PretoE + 5)
				{
					motor[dir] = -40;
					motor[esq] = -40;
				}
				motor[dir] = 0;//2 passo
				motor[esq] = 0;


				if ( EncoderDir > -500 )
				{

					moveMotorTarget(dir,200,40);// passo
					moveMotorTarget(esq,200,40);//
					waitUntilMotorStop(esq);//
					waitUntilMotorStop(dir);//

					moveMotorTarget(dir,Curva90,-40);//5 passof
					moveMotorTarget(esq,Curva90,40);//
					waitUntilMotorStop(esq);//
					waitUntilMotorStop(dir);//


				}
				else
				{
					moveMotorTarget(dir,300,40);// passo
					moveMotorTarget(esq,300,40);//
					waitUntilMotorStop(esq);//
					waitUntilMotorStop(dir);//

					moveMotorTarget(dir,Curva90,-40);//5 passof
					moveMotorTarget(esq,Curva90,40);//
					waitUntilMotorStop(esq);//
					waitUntilMotorStop(dir);//
				}

				while(LuzD > PretoD + 5)
				{//IW
					motor[esq] = 40;
					motor[dir] = 40;
				}//FW

				motor[dir]=0;
				motor[esq]=0;



				moveMotorTarget(dir,190,40);// passo
				moveMotorTarget(esq,190,40);//
				waitUntilMotorStop(esq);//
				waitUntilMotorStop(dir);//


				moveMotorTarget(dir,Curva90,40);// passo
				moveMotorTarget(esq,Curva90,-40);//
				waitUntilMotorStop(esq);//
				waitUntilMotorStop(dir);//

				while(distF > 3)
				{
					startTask(seguir);
					Fmin = 15;
					kp = 1.8;
				}
				stopTask(seguir);
				Fmin = 40;
				kp = 1.5;

				motor[dir]=0;
				motor[esq]=0;

				resetMotorEncoder(dir);
				sleep(150);
				while(EncoderDir > -450)
				{
					motor[dir]= -25;
					motor[esq]= -25;
					if(LuzE < PretoE + 5 && caso != 3 && caso != 4 && caso != 6)
					{
						playTone(130,130);
						caso = 1;
					}
					if(LuzD < PretoD + 5 && caso != 3 && caso != 4 && caso != 6)
					{
						playTone(100,100);
						caso = 2;
					}
					if(LuzE > VerdeE - 10 && LuzE < VerdeE + 10 && greenE - redE > 8 && caso != 5)/////Verde esquerdo
					{
						playTone(40,40);
						caso = 3;
					}
					if(LuzD > VerdeD - 10 && LuzD < VerdeD + 10 && greenD - redD > 8 && caso != 5)//////verde direito
					{
						playTone(70,70);
						caso = 4;
					}
					if(LuzE > VerdeE - 10 && LuzE < VerdeE + 10 && LuzD > VerdeD - 10 && LuzD < VerdeD + 10 && greenE - redE > 8 && greenD - redD > 8 )////beco
					{
						playTone(10,10);
						caso = 5;
					}
					if(LuzD < PretoD + 5 && LuzE < PretoE + 5 && caso != 3 && caso != 4 && caso != 5)////encruzilhada
					{
						playTone(10,10);
						caso = 6;
					}
				}
				motor[dir]= 0;
				motor[esq]= 0;

				if(caso == 0)//////linha reta
				{
					moveMotorTarget(dir,Curva180,-40);// passo
					moveMotorTarget(esq,Curva180,40);//
					waitUntilMotorStop(esq);//
					waitUntilMotorStop(dir);//
				}
				if(caso == 1)/////preto esquerdo
				{
					while(LuzE > PretoE + 10)
					{
						motor[dir]= 25;
						motor[esq]= 25;
					}
					moveMotorTarget(dir,200,40);// passo
					moveMotorTarget(esq,200,40);//
					waitUntilMotorStop(esq);//
					waitUntilMotorStop(dir);//


					moveMotorTarget(dir,Curva90,-40);// passo
					moveMotorTarget(esq,Curva90,40);//
					waitUntilMotorStop(esq);//
					waitUntilMotorStop(dir);//

					while(LuzD > PretoD + 10)
					{
						motor[dir]= -25;
						motor[esq]= -25;
					}
					if(LuzE < PretoE + 10)
					{
						moveMotorTarget(dir,190,40);// passo
						moveMotorTarget(esq,190,40);//
						waitUntilMotorStop(esq);//
						waitUntilMotorStop(dir);//

						moveMotorTarget(dir,Curva90,40);// passo
						moveMotorTarget(esq,Curva90,-40);//
						waitUntilMotorStop(esq);//
						waitUntilMotorStop(dir);//

						moveMotorTarget(dir,200,-40);// passo
						moveMotorTarget(esq,200,-40);//
						waitUntilMotorStop(esq);//
						waitUntilMotorStop(dir);//

						moveMotorTarget(dir,CurvaBeco,40);// passo
						moveMotorTarget(esq,CurvaBeco,-40);//
						waitUntilMotorStop(esq);//
						waitUntilMotorStop(dir);//
					}
					else
					{

						moveMotorTarget(dir,200,40);// passo
						moveMotorTarget(esq,200,40);//
						waitUntilMotorStop(esq);//
						waitUntilMotorStop(dir);//
					}
				}

				if(caso == 2)////preto direito
				{
					while(LuzD > PretoD + 10)
					{
						motor[dir]= 25;
						motor[esq]= 25;
					}
					moveMotorTarget(dir,200,40);// passo
					moveMotorTarget(esq,200,40);//
					waitUntilMotorStop(esq);//
					waitUntilMotorStop(dir);//


					moveMotorTarget(dir,Curva90,40);// passo
					moveMotorTarget(esq,Curva90,-40);//
					waitUntilMotorStop(esq);//
					waitUntilMotorStop(dir);//

					while(LuzE > PretoE + 10)
					{
						motor[dir]= -25;
						motor[esq]= -25;
					}
					if(LuzD < PretoD + 10)
					{
						moveMotorTarget(dir,190,40);// passo
						moveMotorTarget(esq,190,40);//
						waitUntilMotorStop(esq);//
						waitUntilMotorStop(dir);//

						moveMotorTarget(dir,Curva90,-40);// passo
						moveMotorTarget(esq,Curva90,40);//
						waitUntilMotorStop(esq);//
						waitUntilMotorStop(dir);//

						moveMotorTarget(dir,200,-40);// passo
						moveMotorTarget(esq,200,-40);//
						waitUntilMotorStop(esq);//
						waitUntilMotorStop(dir);//

						moveMotorTarget(dir,CurvaBeco,40);// passo
						moveMotorTarget(esq,CurvaBeco,-40);//
						waitUntilMotorStop(esq);//
						waitUntilMotorStop(dir);//
					}
					else
					{

						moveMotorTarget(dir,200,40);// passo
						moveMotorTarget(esq,200,40);//
						waitUntilMotorStop(esq);//
						waitUntilMotorStop(dir);//
					}
				}
				if(caso == 3)/////verde esquerdo
				{
					while(LuzE > PretoE + 10)
					{
						motor[dir]= 25;
						motor[esq]= 25;
					}
					moveMotorTarget(dir,200,40);// passo
					moveMotorTarget(esq,200,40);//
					waitUntilMotorStop(esq);//
					waitUntilMotorStop(dir);//


					moveMotorTarget(dir,Curva90,-40);// passo
					moveMotorTarget(esq,Curva90,40);//
					waitUntilMotorStop(esq);//
					waitUntilMotorStop(dir);//

					moveMotorTarget(dir,100,40);// passo
					moveMotorTarget(esq,100,40);//
					waitUntilMotorStop(esq);//
					waitUntilMotorStop(dir);//

				}
				if(caso == 4)////verde direito
				{
					while(LuzD > PretoD + 10)
					{
						motor[dir]= 25;
						motor[esq]= 25;
					}
					moveMotorTarget(dir,200,40);// passo
					moveMotorTarget(esq,200,40);//
					waitUntilMotorStop(esq);//
					waitUntilMotorStop(dir);//


					moveMotorTarget(dir,Curva90,40);// passo
					moveMotorTarget(esq,Curva90,-40);//
					waitUntilMotorStop(esq);//
					waitUntilMotorStop(dir);//

					moveMotorTarget(dir,100,40);// passo
					moveMotorTarget(esq,100,40);//
					waitUntilMotorStop(esq);//
					waitUntilMotorStop(dir);//
				}
				if(caso == 5)//beco
				{
					while(LuzE > PretoE + 10 && LuzD > PretoD + 10)
					{
						motor[dir]= 30;
						motor[esq]= 30;
					}
					moveMotorTarget(dir,150,40);// passo
					moveMotorTarget(esq,150,40);//
					waitUntilMotorStop(esq);//
					waitUntilMotorStop(dir);//
				}
				if(caso == 6)
				{
					moveMotorTarget(dir,Curva180,-40);// passo
					moveMotorTarget(esq,Curva180,40);//
					waitUntilMotorStop(esq);//
					waitUntilMotorStop(dir);//
				}


				startTask (VerdefakeD);
				startTask (VerdefakeE);
				startTask (VerdeT);
				startTask (seguir);//
			}//Fif distF
		}//Fif = 1
	}//FW1
}//FTOBS

task VerdeT()
{//ITVerdeD
	while(1)
	{//IW
		if( LuzE > VerdeE - 18&& LuzE < VerdeE + 18 && greenE - redE > 5 && VerdeFalsoE == false)
		{//Iif1
			stopTask(seguir);
			motor[esq]=0;
			motor[dir]=0;

			setLEDColor(ledRed);
			stopTask(OBSTACULO1);
			stopTask(OBSTACULO2);
			stopTask(VerdefakeD);
			stopTask(VerdefakeE);
			setLEDColor(ledGreen);

			moveMotorTarget(dir,20,30);
			waitUntilMotorStop(dir);



			if (LuzD > VerdeD - 18&& LuzD < VerdeD + 18 && greenD - redD > 8)
			{//beco
				setLEDColor(ledOrange);
				playTone(130,130);

				moveMotorTarget(dir,150,30);
				moveMotorTarget(esq,150,30);
				waitUntilMotorStop(dir);
				waitUntilMotorStop(esq);
				moveMotorTarget(dir,CurvaBeco,30);
				moveMotorTarget(esq,CurvaBeco,-30);
				waitUntilMotorStop(dir);
				waitUntilMotorStop(esq);

				moveMotorTarget(dir,100,-30);
				moveMotorTarget(esq,100,-30);
				waitUntilMotorStop(dir);
				waitUntilMotorStop(esq);

				setLEDColor(ledGreen);


			}//beco

			else
			{
				playTone(50,50);

				moveMotorTarget(dir,280,30);
				moveMotorTarget(esq,280,30);
				waitUntilMotorStop(dir);
				waitUntilMotorStop(esq);

				moveMotorTarget(dir,curvaVerde,-30);
				moveMotorTarget(esq,curvaVerde,30);
				waitUntilMotorStop(dir);
				waitUntilMotorStop(esq);


			}
			setLEDColor(ledGreen);
			startTask(seguir);
			startTask(OBSTACULO1);
			startTask(OBSTACULO2);
			startTask(VerdefakeD);
			startTask(VerdefakeE);
		}
		else
		{
			if( LuzD > VerdeD - 15 && LuzD < VerdeD + 15 && greenD - redD > 5 && VerdeFalsoD == false)
			{//Iif1
				stopTask(seguir);
				motor[esq]=0;
				motor[dir]=0;


				setLEDColor(ledRed);
				stopTask(OBSTACULO1);
				stopTask(OBSTACULO2);
				stopTask(VerdefakeD);
				stopTask(VerdefakeE);
				setLEDColor(ledGreen);
				moveMotorTarget(dir,20,30);
				waitUntilMotorStop(dir);

				if (LuzE > VerdeE - 15 && LuzE < VerdeE + 15 && greenE - redE > 5 )
				{//beco

					setLEDColor(ledRed);

					moveMotorTarget(dir,150,30);
					moveMotorTarget(esq,150,30);
					waitUntilMotorStop(dir);
					waitUntilMotorStop(esq);
					moveMotorTarget(dir,CurvaBeco,30);
					moveMotorTarget(esq,CurvaBeco,-30);
					waitUntilMotorStop(dir);
					waitUntilMotorStop(esq);

					moveMotorTarget(dir,100,-30);
					moveMotorTarget(esq,100,-30);
					waitUntilMotorStop(dir);
					waitUntilMotorStop(esq);

					sleep(10);

				}//beco
				else
				{
					playTone(50,50);

					moveMotorTarget(dir,280,30);
					moveMotorTarget(esq,280,30);
					waitUntilMotorStop(dir);
					waitUntilMotorStop(esq);
					moveMotorTarget(dir,curvaVerde,30);
					moveMotorTarget(esq,curvaVerde,-30);
					waitUntilMotorStop(dir);
					waitUntilMotorStop(esq);
				}
				setLEDColor(ledGreen);
				startTask(seguir);
				startTask(OBSTACULO1);
				startTask(OBSTACULO2);
				startTask(VerdefakeD);
				startTask(VerdefakeE);
			}//Fif1
		}//Felse
	}//FW
}//FTVerdeD

task VerdefakeE()
{//ITVFE
	while(1)
	{//IW1
		if(LuzE < PretoE && greenE - redE < 5 )
		{//Iif1

			clearTimer(T1);
			controle1 = true;
			while(time1[T1] <= 850 && controle1 == true)
			{//IW2
				VerdeFalsoE = true;
				setLEDColor(ledRed);
				if (LuzE > VerdeEF - 15 && LuzE < VerdeEF + 15 && greenE - redE > 5)
				{//Iif2
					VerdeFalsoD = false;
					stopTask(VerdeT);
					stopTask(seguir);

					motor[esq]=0;
					motor[dir]=0;

					moveMotorTarget(esq,100,50);
					moveMotorTarget(dir,100,50);
					waitUntilMotorStop(esq);
					waitUntilMotorStop(dir);
					controle1= false;

				}//Fif2

			}//FW2
			setLEDColor(ledGreen);
			startTask(seguir);
			startTask(VerdeT);
			VerdeFalsoE = false;
		}//Fif1

	}//FW1*/
}//FTVFE
task VerdefakeD()
{//ITVFE
	while(1)
	{//IW1
		if(LuzD < PretoD && greenD - redD < 5)
		{//Iif1

			clearTimer(T2);
			controle2 = true;
			while(time1[T2] <= 850 && controle2 == true)
			{//IW2
				VerdeFalsoD = true;
				setLEDColor(ledRedPulse);
				if (LuzD > VerdeDF - 15 && LuzD < VerdeDF + 15  && greenD - redD > 5 )
				{//Iif2
					VerdeFalsoD = false;
					stopTask(VerdeT);
					stopTask(seguir);

					motor[esq]=0;
					motor[dir]=0;

					moveMotorTarget(esq,100,50);
					moveMotorTarget(dir,100,50);
					waitUntilMotorStop(esq);
					waitUntilMotorStop(dir);
					controle2 = false;

				}//Fif2

			}//FW2
			setLEDColor(ledGreen);
			startTask(seguir);
			startTask(VerdeT);
			VerdeFalsoD = false;
		}//Fif1
	}//FW1
}//FTVFE
task verSala3()
{
	while(1)
	{
		if(distL > 12) clearTimer(T3);

		if(time1[T3] > 7000)
		{
			Fmin = 60;
			while(distL < 20)
			{
				sleep(1);
			}
			startTask (sala3);
		}
	}
}
task sala3()
{
	motor[dir] = 40;
	motor[esq] = 40;
	sleep(1000);
	motor[dir] = 0;
	motor[esq] = 0;


	stopTask (OBSTACULO1);
	stopTask(OBSTACULO2);
	stopTask (VerdeT);
	stopTask (VerdefakeE);
	stopTask (VerdefakeD);
	stopTask (verSala3);
	stopTask (seguir);
	motor[dir] = 0;
	motor[esq] = 0;

	motor[dir] = 50;
	motor[esq] = 50;
	sleep(1000);
	motor[dir] = 0;
	motor[esq] = 0;

	moveMotorTarget(esq,Curva90,70);
	moveMotorTarget(dir,Curva90,-70);
	waitUntilMotorStop(esq);
	waitUntilMotorStop(dir);

	motor[dir] = -15;
	motor[esq] = -15;
	sleep(4500);
	motor[dir] = 0;
	motor[esq] = 0;

	moveMotorTarget(esq,250,70);
	moveMotorTarget(dir,250,70);
	waitUntilMotorStop(esq);
	waitUntilMotorStop(dir);

	moveMotorTarget(esq,Curva90,-70);
	moveMotorTarget(dir,Curva90,70);
	waitUntilMotorStop(esq);
	waitUntilMotorStop(dir);

	while(distF > 7)
	{
		motor[dir] = 70;
		motor[esq] = 70;
	}
	motor[dir] = 0;
	motor[esq] = 0;

	if (LuzD < PretoD + 15 && LuzD > PretoD - 15)
	{
		patamar = 1;
	}
	else
	{
		moveMotorTarget(esq,Curva90,70);
		moveMotorTarget(dir,Curva90,-70);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		motor[dir] = -15;
		motor[esq] = -15;
		sleep(3000);
		motor[dir] = 0;
		motor[esq] = 0;

		moveMotorTarget(esq,300,70);
		moveMotorTarget(dir,300,70);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);


		while(distF > 7)
		{
			motor[dir] = 50;
			motor[esq] = 50;
		}
		motor[dir] = 0;
		motor[esq] = 0;

		if (LuzD < PretoD + 10 && LuzD > PretoD - 10)
		{
			patamar = 2;


		}
		else patamar = 3;

	}//fim else
	//////////////////////////////////////////////////////////////////////
	///////////////////////////////////////////////////////////////////PATAMAR 1
	if(patamar==1)
	{
		playTone(130,130);

		moveMotorTarget(esq,Curva90,-50);
		moveMotorTarget(dir,Curva90,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		motor[dir]=15;
		motor[esq]=15;
		sleep(4500);
		motor[dir]=0;
		motor[esq]=0;


		moveMotorTarget(esq,900,-50);
		moveMotorTarget(dir,900,-50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		moveMotorTarget(esq,Curva90,50);
		moveMotorTarget(dir,Curva90,-50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		motor[dir]=15;
		motor[esq]=15;
		sleep(2500);
		motor[dir]=0;
		motor[esq]=0;

		motor[garra]=50;
		sleep(1000);
		motor[garra]=0;

		motor[dir]=-50;
		motor[esq]=-50;
		sleep(5000);
		motor[dir]=0;
		motor[esq]=0;

		moveMotorTarget(esq,200,70);
		moveMotorTarget(dir,200,70);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		moveMotorTarget(garra,100,-80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,200,-70);
		moveMotorTarget(dir,200,-70);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		sleep(100);

		moveMotorTarget(garra,100,80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,280,70);
		moveMotorTarget(dir,280,70);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		moveMotorTarget(esq,1700,-70);
		waitUntilMotorStop(esq);

		motor[dir]=50;
		motor[esq]=50;
		sleep(2000);
		motor[dir]=0;
		motor[esq]=0;

		motor[dir]=15;
		motor[esq]=15;
		sleep(2000);
		motor[dir]=0;
		motor[esq]=0;


		motor[dir]=-70;
		motor[esq]=-70;
		sleep(4000);
		motor[dir]=0;
		motor[esq]=0;

		moveMotorTarget(esq,200,70);
		moveMotorTarget(dir,200,70);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		moveMotorTarget(garra,100,-80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,200,-70);
		moveMotorTarget(dir,200,-70);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		sleep(100);

		moveMotorTarget(garra,100,80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,280,70);
		moveMotorTarget(dir,280,70);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		moveMotorTarget(dir,1700,-70);
		waitUntilMotorStop(dir);

		motor[dir]=50;
		motor[esq]=50;
		sleep(2000);
		motor[dir]=0;
		motor[esq]=0;

		motor[dir]=15;
		motor[esq]=15;
		sleep(2000);
		motor[dir]=0;
		motor[esq]=0;


		motor[dir]=-70;
		motor[esq]=-70;
		sleep(4000);
		motor[dir]=0;
		motor[esq]=0;

		moveMotorTarget(esq,200,70);
		moveMotorTarget(dir,200,70);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		moveMotorTarget(garra,100,-80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,200,-70);
		moveMotorTarget(dir,200,-70);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		sleep(100);

		moveMotorTarget(garra,100,80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,280,70);
		moveMotorTarget(dir,280,70);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		moveMotorTarget(esq,1700,-70);
		waitUntilMotorStop(esq);

		motor[dir]=50;
		motor[esq]=50;
		sleep(2000);
		motor[dir]=0;
		motor[esq]=0;

		motor[dir]=15;
		motor[esq]=15;
		sleep(2000);
		motor[dir]=0;
		motor[esq]=0;


		motor[dir]=-70;
		motor[esq]=-70;
		sleep(4000);
		motor[dir]=0;
		motor[esq]=0;

		moveMotorTarget(esq,200,70);
		moveMotorTarget(dir,200,70);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		moveMotorTarget(garra,100,-80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,200,-70);
		moveMotorTarget(dir,200,-70);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		sleep(100);

		moveMotorTarget(garra,100,80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,250,50);
		moveMotorTarget(dir,250,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		moveMotorTarget(esq,300,-50);
		moveMotorTarget(dir,300,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		motor[dir]=-50;
		motor[esq]=-50;
		sleep(3500);
		motor[dir]=0;
		motor[esq]=0;

		moveMotorTarget(esq,300,50);
		moveMotorTarget(dir,300,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		motor[garra] = -50;
		sleep(3000);
		motor[garra] = 0;


		///////////////////////////////////////////////////////////////////////////////////FIM PARTE 1///////////////////////


		///////////////////////////////////////////////////////////////////////////////////INICIO PARTE 2////////////////////

		moveMotorTarget(esq,300,50);
		moveMotorTarget(dir,300,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		moveMotorTarget(esq,Curva180,-50);
		moveMotorTarget(dir,Curva180,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		motor[garra] = 50;
		sleep(1000);
		motor[garra] = 0;

		moveMotorTarget(esq,200,-50);
		moveMotorTarget(dir,200,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);


		motor[dir]=-50;
		motor[esq]=-50;
		sleep(4000);
		motor[dir]=0;
		motor[esq]=0;
		moveMotorTarget(esq,200,50);
		moveMotorTarget(dir,200,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		moveMotorTarget(garra,100,-80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,200,-50);
		moveMotorTarget(dir,200,-50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		sleep(100);

		moveMotorTarget(garra,100,80);
		waitUntilMotorStop(garra);



		moveMotorTarget(esq,250,50);
		moveMotorTarget(dir,250,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		moveMotorTarget(esq,300,50);
		moveMotorTarget(dir,300,-50);////////1a curva
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		motor[dir]=-50;
		motor[esq]=-50;
		sleep(6000);
		motor[dir]=0;
		motor[esq]=0;

		moveMotorTarget(esq,200,50);
		moveMotorTarget(dir,200,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		moveMotorTarget(garra,100,-80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,200,-50);
		moveMotorTarget(dir,200,-50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		sleep(100);
		moveMotorTarget(garra,100,80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,300,50);
		moveMotorTarget(dir,300,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		moveMotorTarget(esq,300,50);
		moveMotorTarget(dir,300,-50);////////2a curva
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		motor[dir]=-50;
		motor[esq]=-50;
		sleep(2000);
		motor[dir]=0;
		motor[esq]=0;

		moveMotorTarget(esq,100,50);
		moveMotorTarget(dir,100,-50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		motor[dir]=-50;
		motor[esq]=-50;
		sleep(3000);
		motor[dir]=0;
		motor[esq]=0;

		moveMotorTarget(esq,200,50);
		moveMotorTarget(dir,200,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		moveMotorTarget(garra,100,-80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,200,-50);
		moveMotorTarget(dir,200,-50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		sleep(100);
		moveMotorTarget(garra,100,80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,250,50);
		moveMotorTarget(dir,250,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		moveMotorTarget(esq,300,50);
		moveMotorTarget(dir,300,-50);///////3a curva
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		motor[dir]=-50;
		motor[esq]=-50;
		sleep(5000);
		motor[dir]=0;
		motor[esq]=0;

		moveMotorTarget(esq,300,50);
		moveMotorTarget(dir,300,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		motor[garra] = -50;
		sleep(3000);
		motor[garra] = 0;

		moveMotorTarget(esq,300,50);
		moveMotorTarget(dir,300,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

	}
	//////////////////////////////////////////////////////////////////////////////////////////
	//////////////////////////////////////////////////////////////////////////PATAMAR 2
	///////////////////////////////////////////////////////////////////////////////////////
	if(patamar == 2)
	{
		playTone(130,130);

		moveMotorTarget(esq,Curva90,-50);
		moveMotorTarget(dir,Curva90,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		motor[dir]=15;
		motor[esq]=15;
		sleep(4500);
		motor[dir]=0;
		motor[esq]=0;


		moveMotorTarget(esq,900,-50);
		moveMotorTarget(dir,900,-50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		moveMotorTarget(esq,Curva90,50);
		moveMotorTarget(dir,Curva90,-50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		motor[dir]=15;
		motor[esq]=15;
		sleep(2500);
		motor[dir]=0;
		motor[esq]=0;

		motor[garra]=50;
		sleep(1000);
		motor[garra]=0;

		motor[dir]=-50;
		motor[esq]=-50;
		sleep(5000);
		motor[dir]=0;
		motor[esq]=0;

		moveMotorTarget(esq,200,70);
		moveMotorTarget(dir,200,70);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		moveMotorTarget(garra,100,-80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,200,-70);
		moveMotorTarget(dir,200,-70);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		sleep(100);

		moveMotorTarget(garra,100,80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,280,70);
		moveMotorTarget(dir,280,70);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		moveMotorTarget(esq,1700,-70);
		waitUntilMotorStop(esq);

		motor[dir]=50;
		motor[esq]=50;
		sleep(2000);
		motor[dir]=0;
		motor[esq]=0;

		motor[dir]=15;
		motor[esq]=15;
		sleep(2000);
		motor[dir]=0;
		motor[esq]=0;


		motor[dir]=-70;
		motor[esq]=-70;
		sleep(4000);
		motor[dir]=0;
		motor[esq]=0;

		moveMotorTarget(esq,200,70);
		moveMotorTarget(dir,200,70);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		moveMotorTarget(garra,100,-80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,200,-70);
		moveMotorTarget(dir,200,-70);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		sleep(100);

		moveMotorTarget(garra,100,80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,280,70);
		moveMotorTarget(dir,280,70);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		moveMotorTarget(dir,1700,-70);
		waitUntilMotorStop(dir);

		motor[dir]=50;
		motor[esq]=50;
		sleep(2000);
		motor[dir]=0;
		motor[esq]=0;

		motor[dir]=15;
		motor[esq]=15;
		sleep(2000);
		motor[dir]=0;
		motor[esq]=0;


		motor[dir]=-70;
		motor[esq]=-70;
		sleep(4000);
		motor[dir]=0;
		motor[esq]=0;

		moveMotorTarget(esq,200,70);
		moveMotorTarget(dir,200,70);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		moveMotorTarget(garra,100,-80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,200,-70);
		moveMotorTarget(dir,200,-70);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		sleep(100);

		moveMotorTarget(garra,100,80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,280,70);
		moveMotorTarget(dir,280,70);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		moveMotorTarget(esq,1700,-70);
		waitUntilMotorStop(esq);

		motor[dir]=50;
		motor[esq]=50;
		sleep(2000);
		motor[dir]=0;
		motor[esq]=0;

		motor[dir]=15;
		motor[esq]=15;
		sleep(2000);
		motor[dir]=0;
		motor[esq]=0;


		motor[dir]=-70;
		motor[esq]=-70;
		sleep(4000);
		motor[dir]=0;
		motor[esq]=0;

		moveMotorTarget(esq,200,70);
		moveMotorTarget(dir,200,70);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		moveMotorTarget(garra,100,-80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,200,-70);
		moveMotorTarget(dir,200,-70);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		sleep(100);

		moveMotorTarget(garra,100,80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,250,50);
		moveMotorTarget(dir,250,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		moveMotorTarget(esq,300,-50);
		moveMotorTarget(dir,300,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		motor[dir]=-50;
		motor[esq]=-50;
		sleep(3500);
		motor[dir]=0;
		motor[esq]=0;

		moveMotorTarget(esq,300,50);
		moveMotorTarget(dir,300,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		motor[garra] = -50;
		sleep(3000);
		motor[garra] = 0;


		///////////////////////////////////////////////////////////////////////////////////INICIO PARTE 2////////////////////

		moveMotorTarget(esq,300,50);
		moveMotorTarget(dir,300,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		moveMotorTarget(esq,Curva180,-50);
		moveMotorTarget(dir,Curva180,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		motor[garra] = 50;
		sleep(1000);
		motor[garra] = 0;

		moveMotorTarget(esq,100,-50);
		moveMotorTarget(dir,100,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		motor[dir]=-50;
		motor[esq]=-50;
		sleep(4000);
		motor[dir]=0;
		motor[esq]=0;
		moveMotorTarget(esq,200,50);
		moveMotorTarget(dir,200,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		moveMotorTarget(garra,100,-80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,200,-50);
		moveMotorTarget(dir,200,-50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		sleep(100);

		moveMotorTarget(garra,100,80);
		waitUntilMotorStop(garra);



		moveMotorTarget(esq,300,50);
		moveMotorTarget(dir,300,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		moveMotorTarget(esq,300,50);
		moveMotorTarget(dir,300,-50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		motor[dir]=-50;
		motor[esq]=-50;
		sleep(2000);
		motor[dir]=0;
		motor[esq]=0;

		moveMotorTarget(esq,150,50);
		moveMotorTarget(dir,150,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);


		moveMotorTarget(esq,100,50);
		moveMotorTarget(dir,100,-50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		motor[dir]=-50;
		motor[esq]=-50;
		sleep(3000);
		motor[dir]=0;
		motor[esq]=0;

		moveMotorTarget(esq,200,50);
		moveMotorTarget(dir,200,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		moveMotorTarget(garra,100,-80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,200,-50);
		moveMotorTarget(dir,200,-50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		sleep(100);
		moveMotorTarget(garra,100,80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,300,50);
		moveMotorTarget(dir,300,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		moveMotorTarget(esq,300,50);
		moveMotorTarget(dir,300,-50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		motor[dir]=-50;
		motor[esq]=-50;
		sleep(6000);
		motor[dir]=0;
		motor[esq]=0;

		moveMotorTarget(esq,200,50);
		moveMotorTarget(dir,200,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		moveMotorTarget(garra,100,-80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,200,-50);
		moveMotorTarget(dir,200,-50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		sleep(100);
		moveMotorTarget(garra,100,80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,300,50);
		moveMotorTarget(dir,300,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		moveMotorTarget(esq,300,50);
		moveMotorTarget(dir,300,-50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);



		motor[dir]=-50;
		motor[esq]=-50;
		sleep(5000);
		motor[dir]=0;
		motor[esq]=0;

		moveMotorTarget(esq,300,50);
		moveMotorTarget(dir,300,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		motor[garra] = -50;
		sleep(3000);
		motor[garra] = 0;

		moveMotorTarget(esq,300,50);
		moveMotorTarget(dir,300,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
	}
	///////////////////////////////////////////////////////////
	//////////////////////////////////////////////////////////////////////////////////////////PATAMAR3
	///////////////////////////////////////////////////////////
	if(patamar == 3)
	{
		playTone(130,130);

		moveMotorTarget(esq,Curva90,-50);
		moveMotorTarget(dir,Curva90,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		motor[dir]=15;
		motor[esq]=15;
		sleep(4500);
		motor[dir]=0;
		motor[esq]=0;


		moveMotorTarget(esq,900,-50);
		moveMotorTarget(dir,900,-50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		moveMotorTarget(esq,Curva90,50);
		moveMotorTarget(dir,Curva90,-50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		motor[dir]=15;
		motor[esq]=15;
		sleep(2500);
		motor[dir]=0;
		motor[esq]=0;

		motor[garra]=50;
		sleep(1000);
		motor[garra]=0;

		motor[dir]=-50;
		motor[esq]=-50;
		sleep(5000);
		motor[dir]=0;
		motor[esq]=0;

		moveMotorTarget(esq,200,70);
		moveMotorTarget(dir,200,70);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		moveMotorTarget(garra,100,-80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,200,-70);
		moveMotorTarget(dir,200,-70);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		sleep(100);

		moveMotorTarget(garra,100,80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,280,70);
		moveMotorTarget(dir,280,70);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		moveMotorTarget(esq,1700,-70);
		waitUntilMotorStop(esq);

		motor[dir]=50;
		motor[esq]=50;
		sleep(2000);
		motor[dir]=0;
		motor[esq]=0;

		motor[dir]=15;
		motor[esq]=15;
		sleep(2000);
		motor[dir]=0;
		motor[esq]=0;


		motor[dir]=-70;
		motor[esq]=-70;
		sleep(4000);
		motor[dir]=0;
		motor[esq]=0;

		moveMotorTarget(esq,200,70);
		moveMotorTarget(dir,200,70);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		moveMotorTarget(garra,100,-80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,200,-70);
		moveMotorTarget(dir,200,-70);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		sleep(100);

		moveMotorTarget(garra,100,80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,280,70);
		moveMotorTarget(dir,280,70);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		moveMotorTarget(dir,1700,-70);
		waitUntilMotorStop(dir);

		motor[dir]=50;
		motor[esq]=50;
		sleep(2000);
		motor[dir]=0;
		motor[esq]=0;

		motor[dir]=15;
		motor[esq]=15;
		sleep(2000);
		motor[dir]=0;
		motor[esq]=0;


		motor[dir]=-70;
		motor[esq]=-70;
		sleep(4000);
		motor[dir]=0;
		motor[esq]=0;

		moveMotorTarget(esq,200,70);
		moveMotorTarget(dir,200,70);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		moveMotorTarget(garra,100,-80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,200,-70);
		moveMotorTarget(dir,200,-70);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		sleep(100);

		moveMotorTarget(garra,100,80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,280,70);
		moveMotorTarget(dir,280,70);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		moveMotorTarget(esq,1700,-70);
		waitUntilMotorStop(esq);

		motor[dir]=50;
		motor[esq]=50;
		sleep(2000);
		motor[dir]=0;
		motor[esq]=0;

		motor[dir]=15;
		motor[esq]=15;
		sleep(2000);
		motor[dir]=0;
		motor[esq]=0;


		motor[dir]=-70;
		motor[esq]=-70;
		sleep(4000);
		motor[dir]=0;
		motor[esq]=0;

		moveMotorTarget(esq,200,70);
		moveMotorTarget(dir,200,70);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		moveMotorTarget(garra,100,-80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,200,-70);
		moveMotorTarget(dir,200,-70);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		sleep(100);

		moveMotorTarget(garra,100,80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,250,50);
		moveMotorTarget(dir,250,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		moveMotorTarget(esq,300,50);
		moveMotorTarget(dir,300,-50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		motor[dir]=-50;
		motor[esq]=-50;
		sleep(3500);
		motor[dir]=0;
		motor[esq]=0;

		moveMotorTarget(esq,300,50);
		moveMotorTarget(dir,300,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		motor[garra] = -50;
		sleep(3000);
		motor[garra] = 0;




		/////////////////////////////////////////////////PARTE 2

		moveMotorTarget(esq,300,50);
		moveMotorTarget(dir,300,-50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		motor[garra] = 50;
		sleep(1000);
		motor[garra] = 0;

		motor[dir]=-50;
		motor[esq]=-50;
		sleep(2500);
		motor[dir]=0;
		motor[esq]=0;

		moveMotorTarget(esq,100,50);
		moveMotorTarget(dir,100,-50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		motor[dir]=-50;
		motor[esq]=-50;
		sleep(3000);
		motor[dir]=0;
		motor[esq]=0;

		moveMotorTarget(esq,200,50);
		moveMotorTarget(dir,200,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		moveMotorTarget(garra,100,-80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,200,-50);
		moveMotorTarget(dir,200,-50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		sleep(100);

		moveMotorTarget(garra,100,80);
		waitUntilMotorStop(garra);



		moveMotorTarget(esq,200,50);
		moveMotorTarget(dir,200,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		moveMotorTarget(esq,300,50);
		moveMotorTarget(dir,300,-50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		motor[dir]=-50;
		motor[esq]=-50;
		sleep(4500);
		motor[dir]=0;
		motor[esq]=0;


		moveMotorTarget(esq,200,50);
		moveMotorTarget(dir,200,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		moveMotorTarget(garra,100,-80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,200,-50);
		moveMotorTarget(dir,200,-50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		sleep(100);
		moveMotorTarget(garra,100,80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,200,50);
		moveMotorTarget(dir,200,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		moveMotorTarget(esq,300,50);
		moveMotorTarget(dir,300,-50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		motor[dir]=-50;
		motor[esq]=-50;
		sleep(5000);
		motor[dir]=0;
		motor[esq]=0;

		moveMotorTarget(esq,200,50);
		moveMotorTarget(dir,200,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		moveMotorTarget(garra,100,-80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,200,-50);
		moveMotorTarget(dir,200,-50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
		sleep(100);
		moveMotorTarget(garra,100,80);
		waitUntilMotorStop(garra);

		moveMotorTarget(esq,200,50);
		moveMotorTarget(dir,200,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		moveMotorTarget(esq,300,50);
		moveMotorTarget(dir,300,-50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);



		motor[dir]=-50;
		motor[esq]=-50;
		sleep(5000);
		motor[dir]=0;
		motor[esq]=0;

		moveMotorTarget(esq,300,50);
		moveMotorTarget(dir,300,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);

		motor[garra] = -50;
		sleep(3000);
		motor[garra] = 0;

		moveMotorTarget(esq,300,50);
		moveMotorTarget(dir,300,50);
		waitUntilMotorStop(esq);
		waitUntilMotorStop(dir);
	}
}
